In [19]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

notebook_dir = Path().resolve()
example_notebooks_dir = notebook_dir.parent.parent
bat_autobidding_dir = example_notebooks_dir.parent

sys.path.insert(0, str(example_notebooks_dir))
sys.path.insert(0, str(bat_autobidding_dir))

import pandas as pd

from evaluate_baselines.baselines_finetune import BaseLineTrainer

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Baselines train + eval

This notebook uses `baselines_finetune.py`.

Flow for each model:
1. train best params with `opt_search_*`
2. evaluate on test with `objective_*(eval=True)`

In [20]:
from experiments.exp_configs import RND42N10Config

config = RND42N10Config()
config.ensure_artifact_dirs()

In [21]:
auction_mode = config.auction_mode
best_params_subfolder = config.experiment_name
# metric to optimize: CPC_REL / RMSE / SCR
random_seed = config.random_seed
metric = config.metric
n_trials = config.n_trials

In [22]:
data_config = config.data_config

In [23]:
trainer = BaseLineTrainer(
    data_config=data_config,
    metric=metric,
    auction_mode=auction_mode,
    base_params_subfolder=best_params_subfolder,
    random_state=random_seed
)


def train_and_eval_model(trainer: BaseLineTrainer, model_name: str, n_trials: int = 10):
    # train on train split and save best params
    getattr(trainer, f"opt_search_{model_name}")(n_trials=n_trials)

    # evaluate on test split using saved params
    eval_value = getattr(trainer, f"objective_{model_name}")(None, eval=True)
    return eval_value

In [24]:
models = ["linear", "tapid", "mpid", "broi"]

results = []
for model_name in models:
    print(f"=== {model_name.upper()} | metric={metric} | auction_mode={auction_mode} ===")
    value = train_and_eval_model(trainer, model_name, n_trials=n_trials)
    results.append({"model": model_name, "metric": metric, "objective_value": value})

results_df = pd.DataFrame(results)
results_df.sort_values("objective_value", ascending=(metric != "SCR"))

[I 2026-03-23 21:02:59,345] A new study created in memory with name: no-name-e6931893-544e-47f6-b522-8fc9f96e7509

=== LINEAR | metric=SCR | auction_mode=FPA ===

[I 2026-03-23 21:04:36,117] Trial 0 finished with value: 31458.397667218815 and parameters: {'coef': 0.01328793865387881, 'lower_clip': 17, 'upper_clip': 8, 'factor': 4.123548312237237}. Best is trial 0 with value: 31458.397667218815.

CPC_REL: 4.0322571653428225, rmse: 2.701533477095753, SCR: 31458.397667218815

[I 2026-03-23 21:06:32,311] Trial 1 finished with value: 26826.655274375742 and parameters: {'coef': 0.0029375693580248803, 'lower_clip': 1, 'upper_clip': 1, 'factor': 7.442442267775763}. Best is trial 0 with value: 31458.397667218815.

CPC_REL: 1388.6746026684646, rmse: 1.3544472958596268, SCR: 26826.655274375742

[I 2026-03-23 21:08:28,530] Trial 2 finished with value: 37171.61541529925 and parameters: {'coef': 0.06354535989071641, 'lower_clip': 7, 'upper_clip': 1, 'factor': 9.357403653248662}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 158.8744559285174, rmse: 1.3430244396569224, SCR: 37171.61541529925

[I 2026-03-23 21:10:09,054] Trial 3 finished with value: 32674.94728768776 and parameters: {'coef': 0.31402644034987814, 'lower_clip': 1, 'upper_clip': 1, 'factor': 1.648942796839546}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 3.326679950312605, rmse: 1.6047179337593949, SCR: 32674.94728768776

[I 2026-03-23 21:12:03,894] Trial 4 finished with value: 34709.27821909145 and parameters: {'coef': 0.008177010059741642, 'lower_clip': 4, 'upper_clip': 2, 'factor': 2.092025959267313}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 89.20116149785102, rmse: 1.481239245971503, SCR: 34709.27821909145

[I 2026-03-23 21:13:56,257] Trial 5 finished with value: 36281.87347549421 and parameters: {'coef': 0.06843729362312385, 'lower_clip': 1, 'upper_clip': 1, 'factor': 2.4693908126265605}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 128.3267962313871, rmse: 1.3184685269691963, SCR: 36281.87347549421

[I 2026-03-23 21:15:54,111] Trial 6 finished with value: 34901.3152553894 and parameters: {'coef': 0.023335213830958296, 'lower_clip': 9, 'upper_clip': 1, 'factor': 3.4224852046754637}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 361.0956809484628, rmse: 1.295342997436458, SCR: 34901.3152553894

[I 2026-03-23 21:17:39,354] Trial 7 finished with value: 34605.895255948955 and parameters: {'coef': 0.05983927119887884, 'lower_clip': 1, 'upper_clip': 5, 'factor': 1.6027225871634023}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 4.240025317400157, rmse: 1.5100531004533595, SCR: 34605.895255948955

[I 2026-03-23 21:19:11,545] Trial 8 finished with value: 29290.456901142075 and parameters: {'coef': 0.001567207543048271, 'lower_clip': 17, 'upper_clip': 18, 'factor': 6.551312204785187}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 5.496572593291944, rmse: 3.4197001628406984, SCR: 29290.456901142075

[I 2026-03-23 21:20:51,083] Trial 9 finished with value: 31811.303591359843 and parameters: {'coef': 0.008198019542400773, 'lower_clip': 1, 'upper_clip': 6, 'factor': 2.9062039271774047}. Best is trial 2 with value: 37171.61541529925.

CPC_REL: 3.8878415647574105, rmse: 2.2424243914386115, SCR: 31811.303591359843
Best trial:
Value: 37171.61541529925
Params:
    coef: 0.06354535989071641
    lower_clip: 7
    upper_clip: 1
    factor: 9.357403653248662

[I 2026-03-23 21:22:51,611] A new study created in memory with name: no-name-cd99cf13-a056-4ad8-96a2-31fbf0b25ae4

CPC_REL: 182.69371981120636, rmse: 1.3087288172293368, SCR: 38000.766231548245
=== TAPID | metric=SCR | auction_mode=FPA ===

[I 2026-03-23 21:23:55,297] Trial 0 finished with value: 26354.542753646172 and parameters: {'k_p1': 0.003148911647956862, 'k_i1': 0.6351221010640696, 'k_d1': 0.08471801418819976, 'coef': 0.37261932455399976}. Best is trial 0 with value: 26354.542753646172.

CPC_REL: 2.935950261929102, rmse: 2.64621806686805, SCR: 26354.542753646172

[I 2026-03-23 21:25:07,923] Trial 1 finished with value: 30684.92408538857 and parameters: {'k_p1': 0.00042079886696066364, 'k_i1': 0.0004207053950287938, 'k_d1': 0.0001707396743152812, 'coef': 0.670721300885889}. Best is trial 1 with value: 30684.92408538857.

CPC_REL: 207.78546837985414, rmse: 1.6589765560913308, SCR: 30684.92408538857

[I 2026-03-23 21:26:20,443] Trial 2 finished with value: 26462.433217422207 and parameters: {'k_p1': 0.02537815508265665, 'k_i1': 0.06796578090758151, 'k_d1': 0.00012087541473056971, 'coef': 0.8424210519563055}. Best is trial 1 with value: 30684.92408538857.

CPC_REL: 9.935633320869059, rmse: 3.797687745931516, SCR: 26462.433217422207

[I 2026-03-23 21:27:33,383] Trial 3 finished with value: 23614.085383317368 and parameters: {'k_p1': 0.21368329072358744, 'k_i1': 0.0007068974950624604, 'k_d1': 0.000533703276260396, 'coef': 0.14962783074537747}. Best is trial 1 with value: 30684.92408538857.

CPC_REL: 3.1434654554558765, rmse: 4.21254526607882, SCR: 23614.085383317368

[I 2026-03-23 21:28:39,126] Trial 4 finished with value: 27826.089418092353 and parameters: {'k_p1': 0.0016480446427978971, 'k_i1': 0.012561043700013555, 'k_d1': 0.005342937261279773, 'coef': 0.18962833227129433}. Best is trial 1 with value: 30684.92408538857.

CPC_REL: 137.04607453610012, rmse: 2.29033358843743, SCR: 27826.089418092353

[I 2026-03-23 21:29:52,599] Trial 5 finished with value: 33063.61074572255 and parameters: {'k_p1': 0.0280163515871626, 'k_i1': 0.0003613894271216529, 'k_d1': 0.0014742753159914669, 'coef': 0.22366500795357477}. Best is trial 5 with value: 33063.61074572255.

CPC_REL: 10.691086306722122, rmse: 2.8058940768345852, SCR: 33063.61074572255

[I 2026-03-23 21:31:02,774] Trial 6 finished with value: 26310.46274065112 and parameters: {'k_p1': 0.006672367170464205, 'k_i1': 0.13826232179369857, 'k_d1': 0.0006290644294586153, 'coef': 0.30953114978934915}. Best is trial 5 with value: 33063.61074572255.

CPC_REL: 9.971467067637139, rmse: 3.410475141336868, SCR: 26310.46274065112

[I 2026-03-23 21:32:08,168] Trial 7 finished with value: 27821.83146431722 and parameters: {'k_p1': 0.0234238498471129, 'k_i1': 0.00015339162591163628, 'k_d1': 0.02692646910086179, 'coef': 0.1454525594539987}. Best is trial 5 with value: 33063.61074572255.

CPC_REL: 11.551017169745414, rmse: 2.5190905162206625, SCR: 27821.83146431722

[I 2026-03-23 21:33:14,707] Trial 8 finished with value: 26682.5065797863 and parameters: {'k_p1': 0.00018205657658407274, 'k_i1': 0.6245139574743068, 'k_d1': 0.7286653737491037, 'coef': 0.590754602820555}. Best is trial 5 with value: 33063.61074572255.

CPC_REL: 4.195808924304213, rmse: 2.382993234533333, SCR: 26682.5065797863

[I 2026-03-23 21:34:21,303] Trial 9 finished with value: 26437.466895086684 and parameters: {'k_p1': 0.001653693718282443, 'k_i1': 0.00024586032763280086, 'k_d1': 0.054567254856014755, 'coef': 0.2630342003320024}. Best is trial 5 with value: 33063.61074572255.

CPC_REL: 158.0128288010962, rmse: 2.297007065274253, SCR: 26437.466895086684
Best trial:
Value: 33063.61074572255
Params:
    k_p1: 0.0280163515871626
    k_i1: 0.0003613894271216529
    k_d1: 0.0014742753159914669
    coef: 0.22366500795357477

[I 2026-03-23 21:35:38,798] A new study created in memory with name: no-name-fd5d5129-2a62-4ab7-a965-9095f3bc34f5

CPC_REL: 11.962526644033554, rmse: 3.0049249703531187, SCR: 33976.18641961899
=== MPID | metric=SCR | auction_mode=FPA ===

[I 2026-03-23 21:51:17,702] Trial 1 finished with value: 17035.351674452984 and parameters: {'k_p1': 0.002524146751875186, 'k_p2': 0.022564152021103824, 'k_i1': 0.10317241188817816, 'k_i2': 0.0016479643539316757, 'k_d1': 0.15070338441121134, 'k_d2': 0.002893173958234529, 'alpha': 0.13629475456888998, 'beta': 0.11482802570052487, 'coef': 0.11333522580836253, 'lower_clip': 0.3805863583613719, 'upper_clip': 1.9348522559360541, 'bid_factor': 5.058061207803818}. Best is trial 1 with value: 17035.351674452984.

CPC_REL: 1168.3101758820253, rmse: 1.208553079030902, SCR: 17035.351674452984

[I 2026-03-23 21:51:18,150] Trial 2 finished with value: 17398.475085926257 and parameters: {'k_p1': 0.6720544710253088, 'k_p2': 0.007113940387680872, 'k_i1': 0.00010027401661595186, 'k_i2': 0.050705621792046685, 'k_d1': 0.09130113759867091, 'k_d2': 0.15019577527896075, 'alpha': 0.12519435586421634, 'beta': 0.18859393840042857, 'coef': 0.20825357514552048, 'lower_clip': 0.1074993410981972, 'upper_clip': 4.220172180961304, 'bid_factor': 2.067000950814043}. Best is trial 2 with value: 17398.475085926257.
[I 2026-03-23 21:51:18,340] Trial 4 finished with value: 16955.630484714828 and parameters: {'k_p1': 0.08941318753646244, 'k_p2': 0.011031779380144555, 'k_i1': 0.001537757551982488, 'k_i2': 0.00011755452366711253, 'k_d1': 0.1728405486705314, 'k_d2': 0.05191519744859782, 'alpha': 0.13473402703338616, 'beta': 0.13451484494944552, 'coef': 0.11748097720915505, 'lower_clip': 0.5995387877159846, 'upper_clip': 1.5861898994028523, 'bid_factor': 0.602861830830292}. Best is trial 2 with value: 17398.475085926257.

CPC_REL: 1121.6368552239887, rmse: 1.2026369524938252, SCR: 17398.475085926257
CPC_REL: 1168.28009889377, rmse: 1.2115814935904767, SCR: 16955.630484714828

[I 2026-03-23 21:51:20,483] Trial 3 finished with value: 19886.2925871429 and parameters: {'k_p1': 0.001599327316415891, 'k_p2': 0.0014768702500175777, 'k_i1': 0.016306627017194576, 'k_i2': 0.011935337834785679, 'k_d1': 0.5581700233238844, 'k_d2': 0.04335472819345343, 'alpha': 0.257063645571723, 'beta': 0.30577632040704283, 'coef': 0.655953856170088, 'lower_clip': 0.6979108546278384, 'upper_clip': 1.825212165667284, 'bid_factor': 4.493999345219831}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 498.5651371581981, rmse: 1.1932050391391067, SCR: 19886.2925871429

[I 2026-03-23 21:51:21,309] Trial 5 finished with value: 17630.254533125662 and parameters: {'k_p1': 0.056740491277632546, 'k_p2': 0.003105837002420523, 'k_i1': 0.0011897565636986782, 'k_i2': 0.0006508360231125499, 'k_d1': 0.00836250192398119, 'k_d2': 0.00019875184423275718, 'alpha': 0.16515419603449677, 'beta': 0.17792045296665748, 'coef': 0.6016761177032464, 'lower_clip': 0.4535757866281299, 'upper_clip': 5.20855424752703, 'bid_factor': 11.633995756422406}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 825.6166490261284, rmse: 1.207181767250248, SCR: 17630.254533125662

[I 2026-03-23 21:51:30,202] Trial 0 finished with value: 17181.86798976882 and parameters: {'k_p1': 0.07816826510966438, 'k_p2': 0.0493833479985473, 'k_i1': 0.42813023668057565, 'k_i2': 0.0019695503114647707, 'k_d1': 0.020032412787774723, 'k_d2': 0.00017117558508821345, 'alpha': 0.33434680799959926, 'beta': 0.473215400780657, 'coef': 0.10344690958850995, 'lower_clip': 0.8437964248000379, 'upper_clip': 4.786665079529065, 'bid_factor': 0.6987027606929219}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 1168.3675013589482, rmse: 1.2023767159152101, SCR: 17181.86798976882

[I 2026-03-23 22:00:46,727] Trial 7 finished with value: 17282.134744642477 and parameters: {'k_p1': 0.6892181900748623, 'k_p2': 0.05731184414868952, 'k_i1': 0.05294560042037454, 'k_i2': 0.43476915829753704, 'k_d1': 0.00938237039504046, 'k_d2': 0.10772402412503149, 'alpha': 0.2508289499672179, 'beta': 0.13486281981470702, 'coef': 0.17737073487206045, 'lower_clip': 0.1575726628607663, 'upper_clip': 1.6340933565838092, 'bid_factor': 0.7856930580913088}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 1160.5516430231246, rmse: 1.1997451623959385, SCR: 17282.134744642477

[I 2026-03-23 22:00:47,034] Trial 8 finished with value: 17656.876400843343 and parameters: {'k_p1': 0.001049150601018747, 'k_p2': 0.02118057365508028, 'k_i1': 0.014420696218085094, 'k_i2': 0.20380338899962389, 'k_d1': 0.004833171340185676, 'k_d2': 0.01431591500127107, 'alpha': 0.3967447981906555, 'beta': 0.2040162212415294, 'coef': 0.275496371236144, 'lower_clip': 0.7143545542569576, 'upper_clip': 3.438140055172846, 'bid_factor': 1.4686551387191142}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 1090.544243013701, rmse: 1.2075267572333324, SCR: 17656.876400843343

[I 2026-03-23 22:00:48,576] Trial 6 finished with value: 17263.958656050538 and parameters: {'k_p1': 0.4790242596348837, 'k_p2': 0.0007635244801660237, 'k_i1': 0.0005211361580259564, 'k_i2': 0.010829500776272566, 'k_d1': 0.21391961848777885, 'k_d2': 0.08390805810877258, 'alpha': 0.8422566984955013, 'beta': 0.25301492227081807, 'coef': 0.16245951993389612, 'lower_clip': 0.4175827177188212, 'upper_clip': 3.6103625675963658, 'bid_factor': 7.2972219626863755}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 1168.3769892666282, rmse: 1.202760699147645, SCR: 17263.958656050538

[I 2026-03-23 22:00:50,616] Trial 9 finished with value: 17382.925417420047 and parameters: {'k_p1': 0.0004346427300279738, 'k_p2': 0.0001825775213409466, 'k_i1': 0.0005823502617168626, 'k_i2': 0.0001914275460849262, 'k_d1': 0.00431439575932144, 'k_d2': 0.06912663447931758, 'alpha': 0.26366473552368785, 'beta': 0.23791158606023083, 'coef': 0.5978081518244197, 'lower_clip': 0.14715609462050472, 'upper_clip': 9.840594307219845, 'bid_factor': 13.155790062967169}. Best is trial 3 with value: 19886.2925871429.

CPC_REL: 833.3931737166791, rmse: 1.2088331944354374, SCR: 17382.925417420047
Best trial:
  Value: 19886.2925871429
  Params:
    k_p1: 0.001599327316415891
    k_p2: 0.0014768702500175777
    k_i1: 0.016306627017194576
    k_i2: 0.011935337834785679
    k_d1: 0.5581700233238844
    k_d2: 0.04335472819345343
    alpha: 0.257063645571723
    beta: 0.30577632040704283
    coef: 0.655953856170088
    lower_clip: 0.6979108546278384
    upper_clip: 1.825212165667284
    bid_factor: 4.493999345219831

[I 2026-03-23 22:02:54,778] A new study created in RDB with name: no-name-976d1a74-9f0f-4101-8960-03026820dc8e

CPC_REL: 630.4752417498114, rmse: 1.2006254642625782, SCR: 20718.559628818428
=== BROI | metric=SCR | auction_mode=FPA ===

[I 2026-03-23 22:03:51,399] Trial 0 finished with value: 15571.999546977431 and parameters: {'ro': 0.4082331665966555, 'v_bar': 122.7582671086234}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:04:47,843] Trial 1 finished with value: 15571.999546977431 and parameters: {'ro': 14.071095169064515, 'v_bar': 3.7570597138026454}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:05:44,119] Trial 2 finished with value: 15571.999546977431 and parameters: {'ro': 0.046885748370639885, 'v_bar': 0.04687454996076498}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:06:41,702] Trial 3 finished with value: 15571.999546977431 and parameters: {'ro': 0.017775399007348217, 'v_bar': 53.14343038625027}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:07:38,835] Trial 4 finished with value: 15571.999546977431 and parameters: {'ro': 3.8495830758681158, 'v_bar': 11.1030270073596}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:08:35,681] Trial 5 finished with value: 15571.999546977431 and parameters: {'ro': 0.012261243785158804, 'v_bar': 148.46065326863524}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:09:33,440] Trial 6 finished with value: 15571.999546977431 and parameters: {'ro': 38.05053502753182, 'v_bar': 0.08189867664214782}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:10:30,459] Trial 7 finished with value: 15571.999546977431 and parameters: {'ro': 0.060538915670281045, 'v_bar': 0.06149337057087107}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:11:28,122] Trial 8 finished with value: 15571.999546977431 and parameters: {'ro': 0.20349559513080262, 'v_bar': 1.8071456341395589}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431

[I 2026-03-23 22:12:25,810] Trial 9 finished with value: 15571.999546977431 and parameters: {'ro': 0.7207895500630219, 'v_bar': 0.1788896719299994}. Best is trial 0 with value: 15571.999546977431.

CPC_REL: 1401.9107519602128, rmse: 1.2174532327756844, SCR: 15571.999546977431
Best trial:
  Value: 15571.999546977431
  Params:
    ro: 0.4082331665966555
    v_bar: 122.7582671086234
CPC_REL: 1673.199264722307, rmse: 1.2203193763993325, SCR: 16290.10399082903

    model metric                                    objective_value
3    broi    SCR  (1673.199264722307, 1.2203193763993325, 16290....
2    mpid    SCR  (630.4752417498114, 1.2006254642625782, 20718....
0  linear    SCR  (182.69371981120636, 1.3087288172293368, 38000...
1   tapid    SCR  (11.962526644033554, 3.0049249703531187, 33976...

In [33]:
results_df['SCR'] = results_df['objective_value'].apply(lambda x: x[2])

In [34]:
results_df

,model,metric,objective_value,SCR
0,linear,SCR,"(182.69371981120636, 1.3087288172293368, 38000...",38000.766232
1,tapid,SCR,"(11.962526644033554, 3.0049249703531187, 33976...",33976.186420
2,mpid,SCR,"(630.4752417498114, 1.2006254642625782, 20718....",20718.559629
3,broi,SCR,"(1673.199264722307, 1.2203193763993325, 16290....",16290.103991

In [36]:
results_df.to_csv('outputs/results_baselines.csv')