# 02 May 05 Linear Clip — LR & LR decay search

Фиксируем **LinearBidder bin clip** (как в старом «fixed baseline»), а через Optuna перебираем **скидку MDP для DQN (`dqn_gamma`)**, **стартовые lr** для DQN и RewardNet и **стратегии затухания learning rate**:

- **DQN `dqn_gamma`**: сетка **1.0, 0.999, 0.99** (дисконт по горизонту Q-learning).
- **DQN LR decay**: `ExponentialLR` (несколько множителей по LR), либо без scheduler, либо `CosineAnnealingWarmRestarts` с периодами 2000 / 8000 шагов обучения (один `scheduler.step` на один gradient step).
- **RewardNet**: без decay или `ExponentialLR` с $\gamma \in \{0.9995, 0.9999\}$.

Профиль: `may06_default_linear_clip_lr_scheduler_search` в `profiles.py` (`n_trials=36`). Число триалов можно переопределить константой ниже.

In [1]:
import sys
import pickle
from dataclasses import replace
from pathlib import Path

import pandas as pd

cwd = Path.cwd().resolve()
REPO_ROOT = cwd
while REPO_ROOT != REPO_ROOT.parent and not (REPO_ROOT / 'pyproject.toml').exists():
    REPO_ROOT = REPO_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from example_notebooks.experiments.drlb.profiles import build_config as build_drlb_config
from example_notebooks.experiments.drlb.profiles import get_profile as get_drlb_profile
from example_notebooks.experiments.shared_runner import run_experiment_inprocess

/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
_linear_scr_fpa = Path(REPO_ROOT) / 'example_notebooks' / 'evaluate_baselines' / 'best_params' / 'fpa_baseline_n10_rndm_42' / 'linear_scr_FPA.pkl'
with _linear_scr_fpa.open('rb') as f:
    linear_tuned_params = pickle.load(f)
linear_tuned_params

{'coef': 0.023335213830958296,
 'lower_clip': 9,
 'upper_clip': 1,
 'factor': 3.4224852046754637}

In [3]:
RUN_NAME = 'may06_linear_clip_lr_scheduler_search'
DRLB_PROFILE = 'may05_default_linear_clip_lr_scheduler_search'
VERBOSE = False
SHOW_PROGRESS = True
# None = взять n_trials из профиля (36)
N_TRIALS_OVERRIDE = None

In [4]:
config = build_drlb_config(RUN_NAME, profile=DRLB_PROFILE, split_set='full_train_val_holdout')
if N_TRIALS_OVERRIDE is not None:
    config = replace(config, n_trials=int(N_TRIALS_OVERRIDE))
config = replace(config, refit_on='train_plus_val', max_steps=None)

profile_data = get_drlb_profile(DRLB_PROFILE)
base_drlb_params = dict(profile_data['base_drlb_params'])
reference_model_params = dict(profile_data['reference_model_params'])
base_drlb_params['bid_lower_clip'] = 3
base_drlb_params['bid_upper_clip'] = 8
base_drlb_params['traffic_path'] = str(REPO_ROOT / 'data' / 'traffic_share.csv')

result = run_experiment_inprocess(
    config,
    verbose=VERBOSE,
    show_progress=SHOW_PROGRESS,
    base_drlb_params=base_drlb_params,
    reference_model_params=reference_model_params,
    state_type=profile_data['state_type'],
    objective=profile_data['objective'],
    search_space_fn=profile_data['search_space_fn'],
    n_trials=config.n_trials,
    max_train_steps=config.max_steps,
)

summary = result['summary']
tuning = summary['tuning']
{
    'run_name': config.run_name,
    'profile': DRLB_PROFILE,
    'n_trials': tuning['n_trials'],
    'study_best_val_clicks': tuning['study_best_value'],
    'best_trial': tuning['best_trial_number'],
    'best_params': tuning['best_params'],
    'best_val_metrics': tuning['best_val_metrics'],
    'final_holdout_metrics': summary['final_holdout']['metrics'],
    'diagnostics_png': summary['refit']['combined_diagnostics_plot_path'],
}

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:20<00:00, 241.12step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:18<00:00, 13.53campaign/s, campaign_id=7.46e+7]
[I 2026-05-05 11:59:10,966] A new study created in memory with name: no-name-2484315a-02ef-4ac3-a4fd-99f5890f1fd2
DRLBBidder.fit: 100%|██████████| 48240/48240 [03:15<00:00, 247.36step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.56campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 2001.57:   3%|▎         | 1/36 [03:37<2:07:00, 217.74s/it]

[I 2026-05-05 12:02:48,702] Trial 0 finished with value: 2001.5665756188923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'none'}. Best is trial 0 with value: 2001.5665756188923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:08<00:00, 256.01step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.85campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 2001.57:   6%|▌         | 2/36 [07:07<2:00:42, 213.03s/it]

[I 2026-05-05 12:06:18,437] Trial 1 finished with value: 1921.7589853826462 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0001, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 0 with value: 2001.5665756188923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:07<00:00, 257.20step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.73campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:   8%|▊         | 3/36 [10:37<1:56:26, 211.70s/it]

[I 2026-05-05 12:09:48,557] Trial 2 finished with value: 2324.2645018582307 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:11<00:00, 251.64step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.09campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:  11%|█         | 4/36 [14:10<1:53:08, 212.13s/it]

[I 2026-05-05 12:13:21,331] Trial 3 finished with value: 1921.7589853826462 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0001, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:00<00:00, 267.12step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.63campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:  14%|█▍        | 5/36 [17:33<1:48:00, 209.04s/it]

[I 2026-05-05 12:16:44,894] Trial 4 finished with value: 2091.6337536667206 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'none', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:04<00:00, 261.69step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.75campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:  17%|█▋        | 6/36 [20:58<1:43:47, 207.58s/it]

[I 2026-05-05 12:20:09,645] Trial 5 finished with value: 1578.3566532722186 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:56<00:00, 273.01step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.28campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:  19%|█▉        | 7/36 [24:16<1:38:51, 204.53s/it]

[I 2026-05-05 12:23:27,900] Trial 6 finished with value: 1866.1036872393151 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:50<00:00, 283.64step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.30campaign/s, campaign_id=7.46e+7]
Best trial: 2. Best value: 2324.26:  22%|██▏       | 8/36 [27:27<1:33:25, 200.21s/it]

[I 2026-05-05 12:26:38,857] Trial 7 finished with value: 1910.7601373906978 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'none'}. Best is trial 2 with value: 2324.2645018582307.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:49<00:00, 283.95step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.61campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  25%|██▌       | 9/36 [30:40<1:29:00, 197.81s/it]

[I 2026-05-05 12:29:51,376] Trial 8 finished with value: 2391.6574960735734 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:49<00:00, 285.22step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.40campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  28%|██▊       | 10/36 [33:51<1:24:47, 195.66s/it]

[I 2026-05-05 12:33:02,230] Trial 9 finished with value: 1972.928682217897 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'exp_0.999', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:53<00:00, 277.80step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.43campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  31%|███       | 11/36 [37:07<1:21:37, 195.91s/it]

[I 2026-05-05 12:36:18,724] Trial 10 finished with value: 2244.400838733735 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:41<00:00, 298.16step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.89campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  33%|███▎      | 12/36 [40:08<1:16:32, 191.34s/it]

[I 2026-05-05 12:39:19,584] Trial 11 finished with value: 1957.6400561106198 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:41<00:00, 298.21step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.49campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  36%|███▌      | 13/36 [43:09<1:12:11, 188.31s/it]

[I 2026-05-05 12:42:20,925] Trial 12 finished with value: 1728.6357881617416 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9995', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:39<00:00, 302.24step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.95campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  39%|███▉      | 14/36 [46:08<1:07:58, 185.36s/it]

[I 2026-05-05 12:45:19,491] Trial 13 finished with value: 1957.6400561106198 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:41<00:00, 298.19step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.92campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  42%|████▏     | 15/36 [49:12<1:04:42, 184.86s/it]

[I 2026-05-05 12:48:23,184] Trial 14 finished with value: 2229.9854309544703 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:37<00:00, 305.87step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.54campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  44%|████▍     | 16/36 [52:10<1:00:55, 182.76s/it]

[I 2026-05-05 12:51:21,063] Trial 15 finished with value: 1930.2931068694852 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.999', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:29<00:00, 323.35step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:10<00:00, 24.22campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  47%|████▋     | 17/36 [54:54<56:07, 177.24s/it]

[I 2026-05-05 12:54:05,452] Trial 16 finished with value: 694.3367993428105 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9995', 'reward_net_lr_decay': 'none'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:26<00:00, 329.85step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 18.35campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  50%|█████     | 18/36 [57:39<52:02, 173.46s/it]

[I 2026-05-05 12:56:50,107] Trial 17 finished with value: 2267.637385103384 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.0003, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'none', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:29<00:00, 323.54step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 17.09campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  53%|█████▎    | 19/36 [1:00:27<48:43, 171.98s/it]

[I 2026-05-05 12:59:38,639] Trial 18 finished with value: 2326.004889010454 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:25<00:00, 332.20step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.55campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  56%|█████▌    | 20/36 [1:03:12<45:19, 169.94s/it]

[I 2026-05-05 13:02:23,837] Trial 19 finished with value: 1942.1502450113292 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'none'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:15<00:00, 356.70step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 18.03campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  58%|█████▊    | 21/36 [1:05:46<41:16, 165.11s/it]

[I 2026-05-05 13:04:57,673] Trial 20 finished with value: 2326.004889010454 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:13<00:00, 361.50step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.77campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  61%|██████    | 22/36 [1:08:18<37:37, 161.25s/it]

[I 2026-05-05 13:07:29,937] Trial 21 finished with value: 2326.004889010454 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:13<00:00, 361.86step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.92campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  64%|██████▍   | 23/36 [1:10:50<34:20, 158.47s/it]

[I 2026-05-05 13:10:01,909] Trial 22 finished with value: 2326.004889010454 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:15<00:00, 356.54step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.84campaign/s, campaign_id=7.46e+7]
Best trial: 8. Best value: 2391.66:  67%|██████▋   | 24/36 [1:13:25<31:26, 157.19s/it]

[I 2026-05-05 13:12:36,124] Trial 23 finished with value: 2326.004889010454 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 8 with value: 2391.6574960735734.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:20<00:00, 343.63step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.38campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  69%|██████▉   | 25/36 [1:16:05<29:00, 158.24s/it]

[I 2026-05-05 13:15:16,792] Trial 24 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:19<00:00, 346.29step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.55campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  72%|███████▏  | 26/36 [1:18:45<26:27, 158.71s/it]

[I 2026-05-05 13:17:56,624] Trial 25 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:38<00:00, 305.01step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.07campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  75%|███████▌  | 27/36 [1:21:44<24:42, 164.77s/it]

[I 2026-05-05 13:20:55,533] Trial 26 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:28<00:00, 324.63step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:13<00:00, 19.36campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  78%|███████▊  | 28/36 [1:24:30<22:01, 165.25s/it]

[I 2026-05-05 13:23:41,892] Trial 27 finished with value: 1847.0989835007003 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:14<00:00, 357.84step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:13<00:00, 18.95campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  81%|████████  | 29/36 [1:27:03<18:50, 161.51s/it]

[I 2026-05-05 13:26:14,671] Trial 28 finished with value: 2003.332519479461 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'exp_0.9995', 'reward_net_lr_decay': 'none'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:21<00:00, 339.78step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 17.10campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  83%|████████▎ | 30/36 [1:29:45<16:09, 161.60s/it]

[I 2026-05-05 13:28:56,481] Trial 29 finished with value: 1943.31940495368 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'none', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:25<00:00, 331.55step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.19campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  86%|████████▌ | 31/36 [1:32:30<13:32, 162.56s/it]

[I 2026-05-05 13:31:41,292] Trial 30 finished with value: 2034.0331376413483 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'exp_0.999', 'reward_net_lr_decay': 'none'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:23<00:00, 336.96step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.45campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  89%|████████▉ | 32/36 [1:35:13<10:50, 162.74s/it]

[I 2026-05-05 13:34:24,460] Trial 31 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:28<00:00, 325.16step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.98campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  92%|█████████▏| 33/36 [1:38:02<08:14, 164.69s/it]

[I 2026-05-05 13:37:13,703] Trial 32 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:22<00:00, 338.57step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.66campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  94%|█████████▍| 34/36 [1:40:45<05:27, 163.98s/it]

[I 2026-05-05 13:39:56,018] Trial 33 finished with value: 2466.06143886923 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:20<00:00, 344.07step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.30campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06:  97%|█████████▋| 35/36 [1:43:25<02:42, 162.94s/it]

[I 2026-05-05 13:42:36,530] Trial 34 finished with value: 2340.1159896762174 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:16<00:00, 353.18step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.79campaign/s, campaign_id=7.46e+7]
Best trial: 24. Best value: 2466.06: 100%|██████████| 36/36 [1:46:01<00:00, 176.72s/it]

[I 2026-05-05 13:45:12,824] Trial 35 finished with value: 2021.3662406935068 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 24 with value: 2466.06143886923.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:23<00:00, 336.13step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.67campaign/s, campaign_id=7.46e+7]
DRLBBidder.fit: 100%|██████████| 59520/59520 [02:51<00:00, 346.46step/s]
autobidder_check campaigns: 100%|██████████| 1285/1285 [01:30<00:00, 14.17campaign/s, campaign_id=7.47e+7]
autobidder_check campaigns: 100%|██████████| 1027/1027 [01:08<00:00, 14.96campaign/s, campaign_id=7.46e+7]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.91campaign/s, campaign_id=7.46e+7]

{'run_name': 'may06_linear_clip_lr_scheduler_search',
 'profile': 'may06_default_linear_clip_lr_scheduler_search',
 'n_trials': 36,
 'study_best_val_clicks': 2466.06143886923,
 'best_trial': 24,
 'best_params': {'dqn_gamma': 1.0,
  'dqn_lr': 0.0003,
  'reward_net_lr': 0.01,
  'dqn_lr_decay': 'cosine_T2000',
  'reward_net_lr_decay': 'exp_0.9999'},
 'best_val_metrics': {'cpc_relative': 1051.5463522684306,
  'rmse': 1.2492047379067723,
  'clicks_sum': 2466.06143886923,
  'quickspend': 0.023346303501945526,
  'skipped_campaigns': 0,
  'time_inference_sec': 15.422693967819214,
  'time_overall_sec': 19.623852014541626,
  'average_end_balance_share': 0.7379224599189419,
  'label': 'best_val',
  'train_steps': 48240,
  'last_dqn_loss': 46.39968490600586,
  'last_reward_net_loss': 139.42835998535156,
  'dqn_loss_mean': 23.377484411404275,
  'dqn_loss_p95': 53.39493198394776,
  'reward_net_loss_mean': 240.92280504525235,
  'reward_net_loss_p95': 738.7282714843747,
  'reward_signal_mean': 9.025922114683691,
  'lambda_final': 0.0036699398547393484},
 'final_holdout_metrics': {'cpc_relative': 755.7130030875425,
  'rmse': 1.3463608270351592,
  'clicks_sum': 13682.761130054798,
  'quickspend': 0.022568093385214007,
  'skipped_campaigns': 0,
  'time_inference_sec': 90.70311498641968,
  'time_overall_sec': 114.6219630241394,
  'average_end_balance_share': 0.7456190336712335,
  'label': 'best_refit',
  'train_steps': 59520,
  'last_dqn_loss': 14.589715003967285,
  'last_reward_net_loss': 1047.194580078125,
  'dqn_loss_mean': 11.316322117953723,
  'dqn_loss_p95': 28.13765478134152,
  'reward_net_loss_mean': 578.1498281456713,
  'reward_net_loss_p95': 2325.7589355468745,
  'reward_signal_mean': 11.345115408084952,
  'lambda_final': 0.0024857594471903287},
 'diagnostics_png': '/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/example_notebooks/experiments/drlb/may06_linear_clip_lr_scheduler_search/outputs/drlb_diagnostics.png'}

In [5]:
trials_df = pd.DataFrame(tuning['all_trials_summary'])
if 'clicks_sum' in trials_df.columns:
    trials_df = trials_df.sort_values('clicks_sum', ascending=False)
trials_df

,trial,dqn_gamma,dqn_lr,reward_net_lr,dqn_lr_decay,reward_net_lr_decay,rmse,clicks_sum,cpc_relative,quickspend,last_dqn_loss,last_reward_net_loss,dqn_loss_mean,reward_net_loss_mean
26,26,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
33,33,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
32,32,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
31,31,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
24,24,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
25,25,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
8,8,1.000,0.0003,0.0010,cosine_T2000,exp_0.9999,1.436881,2391.657496,818.878595,0.054475,25.303316,257.954254,21.704505,250.602151
34,34,1.000,0.0003,0.0030,cosine_T8000,exp_0.9999,1.255702,2340.115990,1207.533119,0.027237,24.510843,212.278915,26.648206,197.959975
18,18,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
22,22,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
23,23,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
21,21,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
20,20,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
2,2,0.990,0.0010,0.0010,exp_0.9999,exp_0.9999,1.321737,2324.264502,701.990220,0.050584,9.963318,331.733215,9.618125,291.391354
17,17,0.990,0.0003,0.0030,none,exp_0.9999,1.554490,2267.637385,393.799016,0.089494,2.567739,67.695862,7.437968,236.058267
10,10,0.990,0.0003,0.0010,cosine_T2000,exp_0.9999,1.258771,2244.400839,1830.057661,0.007782,8.014646,264.167786,7.406400,257.687147
14,14,0.990,0.0030,0.0010,cosine_T2000,exp_0.9999,1.307363,2229.985431,623.349057,0.031128,5.010991,254.010956,6.328691,261.202431
4,4,0.999,0.0001,0.0003,none,exp_0.9999,1.611534,2091.633754,390.736032,0.062257,23.947596,121.204544,16.597248,332.593183
30,30,1.000,0.0003,0.0100,exp_0.999,none,1.509410,2034.033138,818.365695,0.062257,24.215765,355.136841,16.855806,517.750316
35,35,1.000,0.0030,0.0100,cosine_T2000,exp_0.9995,1.244046,2021.366241,1517.852789,0.027237,8.613788,169.497772,10.348965,340.286951
28,28,1.000,0.0003,0.0100,exp_0.9995,none,1.632818,2003.332519,859.582843,0.058366,75.164551,1707.218262,23.720450,537.152447
0,0,1.000,0.0030,0.0100,cosine_T8000,none,1.337201,2001.566576,934.398664,0.035019,7.261782,352.678650,17.261542,518.907005
9,9,0.999,0.0001,0.0003,exp_0.999,exp_0.9995,1.491060,1972.928682,934.932190,0.066148,22.784712,190.672043,14.921471,318.693098
13,13,0.990,0.0003,0.0010,exp_0.9999,exp_0.9999,1.858098,1957.640056,275.600454,0.073930,12.912101,215.433548,9.133672,230.674004
11,11,0.990,0.0003,0.0010,exp_0.9999,exp_0.9999,1.858098,1957.640056,275.600454,0.073930,12.912101,215.433548,9.133672,230.674004
29,29,1.000,0.0003,0.0100,none,exp_0.9995,1.597768,1943.319405,507.075982,0.054475,30.550343,945.430664,15.663357,399.295345
19,19,1.000,0.0030,0.0100,cosine_T2000,none,1.352050,1942.150245,2414.300955,0.023346,20.197140,189.647446,17.488435,569.614671
15,15,1.000,0.0003,0.0010,exp_0.999,exp_0.9999,1.500495,1930.293107,974.145015,0.058366,45.549652,204.063950,17.654846,243.815896
1,1,1.000,0.0001,0.0030,cosine_T8000,exp_0.9995,2.250014,1921.758985,119.389007,0.167315,42.608055,875.815796,13.880794,317.619664
3,3,1.000,0.0001,0.0030,cosine_T8000,exp_0.9995,2.250014,1921.758985,119.389007,0.167315,42.608055,875.815796,13.880794,317.619664
7,7,1.000,0.0010,0.0003,cosine_T8000,none,2.178082,1910.760137,119.692109,0.151751,14.446541,245.455688,14.768595,250.032961
6,6,0.999,0.0001,0.0010,cosine_T2000,exp_0.9999,1.617531,1866.103687,234.493129,0.066148,17.987564,400.993927,10.986794,246.558299
27,27,0.999,0.0003,0.0100,cosine_T2000,exp_0.9999,2.204086,1847.098984,196.831793,0.143969,45.320210,205.250885,18.555789,295.754171
12,12,0.990,0.0010,0.0010,exp_0.9995,exp_0.9999,2.140997,1728.635788,198.014990,0.136187,9.546914,322.168335,8.975524,235.548092
5,5,1.000,0.0010,0.0100,exp_0.9999,exp_0.9995,2.730998,1578.356653,84.346914,0.178988,14.353177,284.107849,19.478942,407.182788
16,16,0.990,0.0010,0.0010,exp_0.9995,none,6.671739,694.336799,83.533605,0.295720,13.334623,368.295868,13.288966,293.963736

In [6]:
pd.DataFrame([
    {'artifact': 'run_summary_json', 'path': str(config.outputs_dir / 'run_summary.json')},
    {'artifact': 'metrics_json', 'path': str(config.outputs_dir / 'metrics.json')},
    {'artifact': 'drlb_diagnostics_png', 'path': str(config.outputs_dir / 'drlb_diagnostics.png')},
    {'artifact': 'best_refit_model', 'path': str(config.best_models_dir / 'best_refit.pt')},
])

               artifact                                               path
0      run_summary_json  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
1          metrics_json  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
2  drlb_diagnostics_png  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
3      best_refit_model  /Users/amsafin/code/local_ml/rl/bat-autobiddin...