# 02 May 05 Linear Clip — LR & LR decay search

Фиксируем **LinearBidder bin clip** (как в старом «fixed baseline»), а через Optuna перебираем **скидку MDP для DQN (`dqn_gamma`)**, **стартовые lr** для DQN и RewardNet и **стратегии затухания learning rate**:

- **DQN `dqn_gamma`**: сетка **1.0, 0.999, 0.99** (дисконт по горизонту Q-learning).
- **DQN LR decay**: `ExponentialLR` (несколько множителей по LR), либо без scheduler, либо `CosineAnnealingWarmRestarts` с периодами 2000 / 8000 шагов обучения (один `scheduler.step` на один gradient step).
- **RewardNet**: без decay или `ExponentialLR` с $\gamma \in \{0.9995, 0.9999\}$.

Профиль: `may06_default_linear_clip_lr_scheduler_search` в `profiles.py` (`n_trials=36`). Число триалов можно переопределить константой ниже.

In [ ]:
import sys
import pickle
from dataclasses import replace
from pathlib import Path

import pandas as pd

cwd = Path.cwd().resolve()
REPO_ROOT = cwd
while REPO_ROOT != REPO_ROOT.parent and not (REPO_ROOT / 'pyproject.toml').exists():
    REPO_ROOT = REPO_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from example_notebooks.experiments.drlb.profiles import build_config as build_drlb_config
from example_notebooks.experiments.drlb.profiles import get_profile as get_drlb_profile
from example_notebooks.experiments.shared_runner import run_experiment_inprocess

In [ ]:
_linear_scr_fpa = Path(REPO_ROOT) / 'example_notebooks' / 'evaluate_baselines' / 'best_params' / 'fpa_baseline_n10_rndm_42' / 'linear_scr_FPA.pkl'
with _linear_scr_fpa.open('rb') as f:
    linear_tuned_params = pickle.load(f)
linear_tuned_params

{'coef': 0.023335213830958296,
 'lower_clip': 9,
 'upper_clip': 1,
 'factor': 3.4224852046754637}

In [ ]:
RUN_NAME = 'may06_clip_lr_scheduler_search'
DRLB_PROFILE = 'may05_default_clip_lr_scheduler_search'
VERBOSE = False
SHOW_PROGRESS = True
# None = взять n_trials из профиля (36)
N_TRIALS_OVERRIDE = None

In [ ]:
config = build_drlb_config(RUN_NAME, profile=DRLB_PROFILE, split_set='full_train_val_holdout')
if N_TRIALS_OVERRIDE is not None:
    config = replace(config, n_trials=int(N_TRIALS_OVERRIDE))
config = replace(config, refit_on='train_plus_val', max_steps=None)

profile_data = get_drlb_profile(DRLB_PROFILE)
base_drlb_params = dict(profile_data['base_drlb_params'])
reference_model_params = dict(profile_data['reference_model_params'])
base_drlb_params['bid_lower_clip'] = 3
base_drlb_params['bid_upper_clip'] = 8
base_drlb_params['traffic_path'] = str(REPO_ROOT / 'data' / 'traffic_share.csv')

result = run_experiment_inprocess(
    config,
    verbose=VERBOSE,
    show_progress=SHOW_PROGRESS,
    base_drlb_params=base_drlb_params,
    reference_model_params=reference_model_params,
    state_type=profile_data['state_type'],
    objective=profile_data['objective'],
    search_space_fn=profile_data['search_space_fn'],
    n_trials=config.n_trials,
    max_train_steps=config.max_steps,
)

summary = result['summary']
tuning = summary['tuning']
{
    'run_name': config.run_name,
    'profile': DRLB_PROFILE,
    'n_trials': tuning['n_trials'],
    'study_best_val_clicks': tuning['study_best_value'],
    'best_trial': tuning['best_trial_number'],
    'best_params': tuning['best_params'],
    'best_val_metrics': tuning['best_val_metrics'],
    'final_holdout_metrics': summary['final_holdout']['metrics'],
    'diagnostics_png': summary['refit']['combined_diagnostics_plot_path'],
}

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:03<00:00, 262.62step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.49campaign/s, campaign_id=7.46e+7]
[I 2026-05-06 01:13:18,308] A new study created in memory with name: no-name-ab05ce48-e530-4d5f-a765-04e8ad1d3ff1
DRLBBidder.fit: 100%|██████████| 48240/48240 [02:56<00:00, 273.67step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:19<00:00, 13.28campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 1654.88:   3%|▎         | 1/36 [03:20<1:57:06, 200.77s/it]

[I 2026-05-06 01:16:39,075] Trial 0 finished with value: 1654.8796704626443 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.003, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'none'}. Best is trial 0 with value: 1654.8796704626443.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:53<00:00, 277.50step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.50campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 1654.88:   6%|▌         | 2/36 [06:35<1:51:43, 197.16s/it]

[I 2026-05-06 01:19:53,699] Trial 1 finished with value: 1546.8655996726086 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0001, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 0 with value: 1654.8796704626443.

DRLBBidder.fit: 100%|██████████| 48240/48240 [03:01<00:00, 266.48step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:12<00:00, 20.56campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 1654.88:   8%|▊         | 3/36 [09:53<1:48:44, 197.72s/it]

[I 2026-05-06 01:23:12,096] Trial 2 finished with value: 1175.2450333268318 and parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 0 with value: 1654.8796704626443.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:46<00:00, 290.29step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.88campaign/s, campaign_id=7.46e+7]
Best trial: 0. Best value: 1654.88:  11%|█         | 4/36 [12:59<1:42:51, 192.86s/it]

[I 2026-05-06 01:26:17,492] Trial 3 finished with value: 1546.8655996726086 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0001, 'reward_net_lr': 0.003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 0 with value: 1654.8796704626443.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:39<00:00, 301.56step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.38campaign/s, campaign_id=7.46e+7]
Best trial: 4. Best value: 1984.4:  14%|█▍        | 5/36 [16:00<1:37:31, 188.74s/it]

[I 2026-05-06 01:29:18,948] Trial 4 finished with value: 1984.3973146606863 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'none', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 4 with value: 1984.3973146606863.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:38<00:00, 304.89step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 17.82campaign/s, campaign_id=7.46e+7]
Best trial: 4. Best value: 1984.4:  17%|█▋        | 6/36 [18:58<1:32:28, 184.94s/it]

[I 2026-05-06 01:32:16,494] Trial 5 finished with value: 1615.343090246939 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.01, 'dqn_lr_decay': 'exp_0.9999', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 4 with value: 1984.3973146606863.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:36<00:00, 307.35step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:15<00:00, 16.49campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  19%|█▉        | 7/36 [21:55<1:28:12, 182.49s/it]

[I 2026-05-06 01:35:13,953] Trial 6 finished with value: 2070.5456830456856 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:42<00:00, 296.65step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.57campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  22%|██▏       | 8/36 [24:59<1:25:22, 182.94s/it]

[I 2026-05-06 01:38:17,856] Trial 7 finished with value: 1975.3982101498277 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'cosine_T8000', 'reward_net_lr_decay': 'none'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:52<00:00, 279.21step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:14<00:00, 18.31campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  25%|██▌       | 9/36 [28:11<1:23:33, 185.70s/it]

[I 2026-05-06 01:41:29,626] Trial 8 finished with value: 1446.5765182787804 and parameters: {'dqn_gamma': 1.0, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:54<00:00, 276.56step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.42campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  28%|██▊       | 10/36 [31:27<1:21:51, 188.90s/it]

[I 2026-05-06 01:44:45,672] Trial 9 finished with value: 1953.2245836309312 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0001, 'reward_net_lr': 0.0003, 'dqn_lr_decay': 'exp_0.999', 'reward_net_lr_decay': 'exp_0.9995'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:52<00:00, 278.86step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:17<00:00, 14.70campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  31%|███       | 11/36 [34:42<1:19:32, 190.91s/it]

[I 2026-05-06 01:48:01,139] Trial 10 finished with value: 2032.6140998122014 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [02:51<00:00, 281.48step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.22campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  33%|███▎      | 12/36 [37:56<1:16:38, 191.60s/it]

[I 2026-05-06 01:51:14,341] Trial 11 finished with value: 2032.6140998122014 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [5:00:35<00:00,  2.67step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [49:43<00:00, 11.61s/campaign, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  36%|███▌      | 13/36 [6:43:47<43:20:20, 6783.50s/it]

[I 2026-05-06 07:57:06,023] Trial 12 finished with value: 2032.6140998122014 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit: 100%|██████████| 48240/48240 [1:13:36<00:00, 10.92step/s]
autobidder_check campaigns: 100%|██████████| 257/257 [00:16<00:00, 15.68campaign/s, campaign_id=7.46e+7]
Best trial: 6. Best value: 2070.55:  39%|███▉      | 14/36 [7:57:45<37:07:27, 6074.88s/it]

[I 2026-05-06 09:11:03,476] Trial 13 finished with value: 1885.7283864153887 and parameters: {'dqn_gamma': 0.999, 'dqn_lr': 0.003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'exp_0.9995', 'reward_net_lr_decay': 'exp_0.9999'}. Best is trial 6 with value: 2070.5456830456856.

DRLBBidder.fit:  52%|█████▏    | 25050/48240 [01:29<01:23, 278.66step/s]
Best trial: 6. Best value: 2070.55:  39%|███▉      | 14/36 [7:59:15<12:33:06, 2053.95s/it]

[W 2026-05-06 09:12:33,596] Trial 14 failed with parameters: {'dqn_gamma': 0.99, 'dqn_lr': 0.0003, 'reward_net_lr': 0.001, 'dqn_lr_decay': 'cosine_T2000', 'reward_net_lr_decay': 'exp_0.9999'} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/example_notebooks/experiments/adapters/drlb_adapter.py", line 144, in optuna_objective
    run = run_drlb_candidate(
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/example_notebooks/experiments/adapters/drlb_adapter.py", line 354, in run_drlb_candidate
    bidder.fit(
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/simulator/model/drlb_bidder.py", line 524, in fit
    self.agent.learn_dqn_transition(
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/simulator/model/drlb/rl_bid_agent_bat.py", line 115, in learn_dqn_transition
    self.dqn_agent.step(
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/simulator/model/drlb/dqn.py", line 111, in step
    experiences = self.memory.sample()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/simulator/model/drlb/replay_buffer.py", line 50, in sample
    return self._collate_fn(transitions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat-autobidding-benchmark/simulator/model/drlb/replay_buffer.py", line 59, in collate_q_transitions
    rewards = torch.from_numpy(np.vstack([t.reward for t in transitions])).float().to(device)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/numpy/core/shape_base.py", line 286, in vstack
    arrs = atleast_2d(*tup)
           ^^^^^^^^^^^^^^^^
  File "/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/numpy/core/shape_base.py", line 77, in _atleast_2d_dispatcher
    def _atleast_2d_dispatcher(*arys):

KeyboardInterrupt
[W 2026-05-06 09:12:33,601] Trial 14 failed with value None.

KeyboardInterrupt:

In [ ]:
trials_df = pd.DataFrame(tuning['all_trials_summary'])
if 'clicks_sum' in trials_df.columns:
    trials_df = trials_df.sort_values('clicks_sum', ascending=False)
trials_df

,trial,dqn_gamma,dqn_lr,reward_net_lr,dqn_lr_decay,reward_net_lr_decay,rmse,clicks_sum,cpc_relative,quickspend,last_dqn_loss,last_reward_net_loss,dqn_loss_mean,reward_net_loss_mean
26,26,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
33,33,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
32,32,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
31,31,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
24,24,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
25,25,1.000,0.0003,0.0100,cosine_T2000,exp_0.9999,1.249205,2466.061439,1051.546352,0.023346,46.399685,139.428360,23.377484,240.922805
8,8,1.000,0.0003,0.0010,cosine_T2000,exp_0.9999,1.436881,2391.657496,818.878595,0.054475,25.303316,257.954254,21.704505,250.602151
34,34,1.000,0.0003,0.0030,cosine_T8000,exp_0.9999,1.255702,2340.115990,1207.533119,0.027237,24.510843,212.278915,26.648206,197.959975
18,18,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
22,22,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
23,23,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
21,21,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
20,20,1.000,0.0010,0.0100,cosine_T2000,exp_0.9999,1.401908,2326.004889,974.469456,0.058366,28.818624,117.121498,16.557584,255.321782
2,2,0.990,0.0010,0.0010,exp_0.9999,exp_0.9999,1.321737,2324.264502,701.990220,0.050584,9.963318,331.733215,9.618125,291.391354
17,17,0.990,0.0003,0.0030,none,exp_0.9999,1.554490,2267.637385,393.799016,0.089494,2.567739,67.695862,7.437968,236.058267
10,10,0.990,0.0003,0.0010,cosine_T2000,exp_0.9999,1.258771,2244.400839,1830.057661,0.007782,8.014646,264.167786,7.406400,257.687147
14,14,0.990,0.0030,0.0010,cosine_T2000,exp_0.9999,1.307363,2229.985431,623.349057,0.031128,5.010991,254.010956,6.328691,261.202431
4,4,0.999,0.0001,0.0003,none,exp_0.9999,1.611534,2091.633754,390.736032,0.062257,23.947596,121.204544,16.597248,332.593183
30,30,1.000,0.0003,0.0100,exp_0.999,none,1.509410,2034.033138,818.365695,0.062257,24.215765,355.136841,16.855806,517.750316
35,35,1.000,0.0030,0.0100,cosine_T2000,exp_0.9995,1.244046,2021.366241,1517.852789,0.027237,8.613788,169.497772,10.348965,340.286951
28,28,1.000,0.0003,0.0100,exp_0.9995,none,1.632818,2003.332519,859.582843,0.058366,75.164551,1707.218262,23.720450,537.152447
0,0,1.000,0.0030,0.0100,cosine_T8000,none,1.337201,2001.566576,934.398664,0.035019,7.261782,352.678650,17.261542,518.907005
9,9,0.999,0.0001,0.0003,exp_0.999,exp_0.9995,1.491060,1972.928682,934.932190,0.066148,22.784712,190.672043,14.921471,318.693098
13,13,0.990,0.0003,0.0010,exp_0.9999,exp_0.9999,1.858098,1957.640056,275.600454,0.073930,12.912101,215.433548,9.133672,230.674004
11,11,0.990,0.0003,0.0010,exp_0.9999,exp_0.9999,1.858098,1957.640056,275.600454,0.073930,12.912101,215.433548,9.133672,230.674004
29,29,1.000,0.0003,0.0100,none,exp_0.9995,1.597768,1943.319405,507.075982,0.054475,30.550343,945.430664,15.663357,399.295345
19,19,1.000,0.0030,0.0100,cosine_T2000,none,1.352050,1942.150245,2414.300955,0.023346,20.197140,189.647446,17.488435,569.614671
15,15,1.000,0.0003,0.0010,exp_0.999,exp_0.9999,1.500495,1930.293107,974.145015,0.058366,45.549652,204.063950,17.654846,243.815896
1,1,1.000,0.0001,0.0030,cosine_T8000,exp_0.9995,2.250014,1921.758985,119.389007,0.167315,42.608055,875.815796,13.880794,317.619664
3,3,1.000,0.0001,0.0030,cosine_T8000,exp_0.9995,2.250014,1921.758985,119.389007,0.167315,42.608055,875.815796,13.880794,317.619664
7,7,1.000,0.0010,0.0003,cosine_T8000,none,2.178082,1910.760137,119.692109,0.151751,14.446541,245.455688,14.768595,250.032961
6,6,0.999,0.0001,0.0010,cosine_T2000,exp_0.9999,1.617531,1866.103687,234.493129,0.066148,17.987564,400.993927,10.986794,246.558299
27,27,0.999,0.0003,0.0100,cosine_T2000,exp_0.9999,2.204086,1847.098984,196.831793,0.143969,45.320210,205.250885,18.555789,295.754171
12,12,0.990,0.0010,0.0010,exp_0.9995,exp_0.9999,2.140997,1728.635788,198.014990,0.136187,9.546914,322.168335,8.975524,235.548092
5,5,1.000,0.0010,0.0100,exp_0.9999,exp_0.9995,2.730998,1578.356653,84.346914,0.178988,14.353177,284.107849,19.478942,407.182788
16,16,0.990,0.0010,0.0010,exp_0.9995,none,6.671739,694.336799,83.533605,0.295720,13.334623,368.295868,13.288966,293.963736

In [ ]:
pd.DataFrame([
    {'artifact': 'run_summary_json', 'path': str(config.outputs_dir / 'run_summary.json')},
    {'artifact': 'metrics_json', 'path': str(config.outputs_dir / 'metrics.json')},
    {'artifact': 'drlb_diagnostics_png', 'path': str(config.outputs_dir / 'drlb_diagnostics.png')},
    {'artifact': 'best_refit_model', 'path': str(config.best_models_dir / 'best_refit.pt')},
])

               artifact                                               path
0      run_summary_json  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
1          metrics_json  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
2  drlb_diagnostics_png  /Users/amsafin/code/local_ml/rl/bat-autobiddin...
3      best_refit_model  /Users/amsafin/code/local_ml/rl/bat-autobiddin...