In [1]:
import sys
sys.path.append("../../")

%load_ext autoreload
%autoreload 2

import pandas as pd

from baselines_finetune import BaseLineTrainer

/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Baselines train + eval

This notebook uses `baselines_finetune.py`.

Flow for each model:
1. train best params with `opt_search_*`
2. evaluate on test with `objective_*(eval=True)`

In [2]:
auction_mode = "FPA"  # or "VCG"
best_params_subfolder = f"{auction_mode.lower()}_baseline_n10_rndm_42"

# metric to optimize: CPC_REL / RMSE / SCR
metric = "SCR"
n_trials = 10

In [3]:
data_config = {
    "train": {
        "campaigns_path": f"../../data/{auction_mode.lower()}/campaigns_{auction_mode.lower()}_filtered_train_final.csv",
        "stats_path": f"../../data/{auction_mode.lower()}/stats_{auction_mode.lower()}_filtered_train_final.csv",
    },
    "test": {
        "campaigns_path": f"../../data/{auction_mode.lower()}/campaigns_{auction_mode.lower()}_filtered_test_final.csv",
        "stats_path": f"../../data/{auction_mode.lower()}/stats_{auction_mode.lower()}_filtered_test_final.csv",
    },
}

data_config

{'train': {'campaigns_path': '../../data/fpa/campaigns_fpa_filtered_train_final.csv',
  'stats_path': '../../data/fpa/stats_fpa_filtered_train_final.csv'},
 'test': {'campaigns_path': '../../data/fpa/campaigns_fpa_filtered_test_final.csv',
  'stats_path': '../../data/fpa/stats_fpa_filtered_test_final.csv'}}

In [4]:
trainer = BaseLineTrainer(
    data_config=data_config,
    metric=metric,
    auction_mode=auction_mode,
    base_params_subfolder=best_params_subfolder,
    random_state=42,
)

In [6]:
models = ["broi"]  # e.g. ["linear", "tapid", "mpid", "broi"]

rows = []
for model_name in models:
    print(f"=== {model_name.upper()} | metric={metric} | auction_mode={auction_mode} ===")
    getattr(trainer, f"opt_search_{model_name}")(n_trials=n_trials)
    score = getattr(trainer, f"objective_{model_name}")(None, eval=True)
    cpc, rmse, scr = score[0], score[1], score[2]
    rows.append({"model": model_name, "CPC_REL": cpc, "RMSE": rmse, "SCR": scr})

results_df = pd.DataFrame(rows)
sort_col = {"SCR": "SCR", "RMSE": "RMSE", "CPC_REL": "CPC_REL"}[metric]
results_df.sort_values(sort_col, ascending=(metric != "SCR")).reset_index(drop=True)

[I 2026-04-28 00:30:23,553] A new study created in memory with name: no-name-3cf48cc0-5f86-4596-ba5a-b8ab1bdd79df

=== BROI | metric=SCR | auction_mode=FPA ===

[I 2026-04-28 00:31:24,243] Trial 0 finished with value: 12756.038643194499 and parameters: {'ro': 0.4082331665966555, 'v_bar': 122.7582671086234}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:32:24,808] Trial 1 finished with value: 12756.038643194499 and parameters: {'ro': 14.071095169064515, 'v_bar': 3.7570597138026454}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:33:24,178] Trial 2 finished with value: 12756.038643194499 and parameters: {'ro': 0.046885748370639885, 'v_bar': 0.04687454996076498}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:34:22,421] Trial 3 finished with value: 12756.038643194499 and parameters: {'ro': 0.017775399007348217, 'v_bar': 53.14343038625027}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:35:20,022] Trial 4 finished with value: 12756.038643194499 and parameters: {'ro': 3.8495830758681158, 'v_bar': 11.1030270073596}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:36:17,317] Trial 5 finished with value: 12756.038643194499 and parameters: {'ro': 0.012261243785158804, 'v_bar': 148.46065326863524}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:37:15,816] Trial 6 finished with value: 12756.038643194499 and parameters: {'ro': 38.05053502753182, 'v_bar': 0.08189867664214782}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:38:16,503] Trial 7 finished with value: 12756.038643194499 and parameters: {'ro': 0.060538915670281045, 'v_bar': 0.06149337057087107}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:39:16,163] Trial 8 finished with value: 12756.038643194499 and parameters: {'ro': 0.20349559513080262, 'v_bar': 1.8071456341395589}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499

[I 2026-04-28 00:40:13,726] Trial 9 finished with value: 12756.038643194499 and parameters: {'ro': 0.7207895500630219, 'v_bar': 0.1788896719299994}. Best is trial 0 with value: 12756.038643194499.

CPC_REL: 1402.2010767493412, rmse: 1.2083194056139834, SCR: 12756.038643194499
Best trial:
  Value: 12756.038643194499
  Params:
    ro: 0.4082331665966555
    v_bar: 122.7582671086234
CPC_REL: 1673.5800751388574, rmse: 1.1907623178813065, SCR: 13309.890588604083

  model metric                                    objective_value
0  broi    SCR  (1673.5800751388574, 1.1907623178813065, 13309...

### Notes

- `objective_*(eval=True)` loads params from:
  `best_params/{best_params_subfolder}/{model}_{metric}_{auction_mode}.pkl`
- This notebook currently runs: `linear`, `tapid`, `mpid`, `mystique`.
- `broi` is not included in this run block.

### Скоры val / test по сохранённым `.pkl`

Ниже: все `*{metric}_{auction}.pkl` из папки `trainer` + `autobidder_check` на каждом из `val`, `test`, если ключ есть в `data_config`.

In [12]:
from pathlib import Path
import pickle

from example_notebooks.experiments.adapters.baseline_adapter import (
    _MODEL_TO_BIDDER,
    _build_bidder_eval_params,
)
from simulator.validation.check_results import autobidder_check

params_dir = Path(trainer.get_params_path("linear")).parent
suffix = f"_{trainer.metric.lower()}_{trainer.auction_mode}.pkl"

rows = []
for split in ("val", "test"):
    if split not in data_config:
        continue
    sp = data_config[split]
    for path in sorted(params_dir.glob(f"*{suffix}")):
        stem = path.name[: -len(suffix)]
        d = pickle.loads(path.read_bytes())
        bidder = _MODEL_TO_BIDDER[stem]
        p = _build_bidder_eval_params(stem, d)
        sc = autobidder_check(
            bidder=bidder,
            params={"input_campaigns": sp["campaigns_path"], "input_stats": sp["stats_path"], **p},
            auction_mode=trainer.auction_mode,
        )["score"]
        rows.append({"split": split, "model": stem, "CPC_REL": sc[0], "RMSE": sc[1], "SCR": sc[2]})

baseline_scores_df = pd.DataFrame(rows).sort_values(["split", "model"]).reset_index(drop=True)
baseline_scores_df

  split   model      CPC_REL      RMSE           SCR
0  test    broi  5906.638103  1.229709   4599.856980
1  test  linear   421.338042  1.503115  17792.733546
2  test   m_pid   918.943912  1.332016  13807.015982
3  test  ta_pid    41.741961  5.574081   6029.365250