In [1]:
import sys
sys.path.append("../../")

%load_ext autoreload
%autoreload 2

import pandas as pd

from baselines_finetune import BaseLineTrainer

/Users/amsafin/code/local_ml/rl/bat_venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Baselines train + eval

This notebook uses `baselines_finetune.py`.

Flow for each model:
1. train best params with `opt_search_*`
2. evaluate on test with `objective_*(eval=True)`

In [2]:
auction_mode = "FPA"  # or "VCG"
best_params_subfolder = f"{auction_mode.lower()}_baseline_n10_rndm_42"

# metric to optimize: CPC_REL / RMSE / SCR
metric = "SCR"
n_trials = 50

In [3]:
data_config = {
    "train": {
        "campaigns_path": f"../../data/{auction_mode.lower()}/campaigns_{auction_mode.lower()}_filtered_train_final.csv",
        "stats_path": f"../../data/{auction_mode.lower()}/stats_{auction_mode.lower()}_filtered_train_final.csv",
    },
    "test": {
        "campaigns_path": f"../../data/{auction_mode.lower()}/campaigns_{auction_mode.lower()}_filtered_test_final.csv",
        "stats_path": f"../../data/{auction_mode.lower()}/stats_{auction_mode.lower()}_filtered_test_final.csv",
    },
}

data_config

{'train': {'campaigns_path': '../../data/fpa/campaigns_fpa_filtered_train_final.csv',
  'stats_path': '../../data/fpa/stats_fpa_filtered_train_final.csv'},
 'test': {'campaigns_path': '../../data/fpa/campaigns_fpa_filtered_test_final.csv',
  'stats_path': '../../data/fpa/stats_fpa_filtered_test_final.csv'}}

In [4]:
trainer = BaseLineTrainer(
    data_config=data_config,
    metric=metric,
    auction_mode=auction_mode,
    base_params_subfolder=best_params_subfolder,
    random_state=42,
)

In [5]:
# models = ["broi"]  # e.g. ["linear", "tapid", "mpid", "broi"]
models = ["tapid", "mpid", "broi"]

rows = []
for model_name in models:
    print(f"=== {model_name.upper()} | metric={metric} | auction_mode={auction_mode} ===")
    getattr(trainer, f"opt_search_{model_name}")(n_trials=n_trials)
    score = getattr(trainer, f"objective_{model_name}")(None, eval=True)
    cpc, rmse, scr = score[0], score[1], score[2]
    rows.append({"model": model_name, "CPC_REL": cpc, "RMSE": rmse, "SCR": scr})

results_df = pd.DataFrame(rows)
sort_col = {"SCR": "SCR", "RMSE": "RMSE", "CPC_REL": "CPC_REL"}[metric]
results_df.sort_values(sort_col, ascending=(metric != "SCR")).reset_index(drop=True)

[I 2026-04-28 12:48:57,588] A new study created in memory with name: no-name-bf557092-73df-4dfb-bf68-0914bb339faf

=== TAPID | metric=SCR | auction_mode=FPA ===

[I 2026-04-28 12:49:38,020] Trial 0 finished with value: 3069.5665683207426 and parameters: {'k_p1': 0.003148911647956862, 'k_i1': 0.6351221010640696, 'k_d1': 0.08471801418819976, 'coef': 0.37261932455399976}. Best is trial 0 with value: 3069.5665683207426.

CPC_REL: 11.65475727462579, rmse: 7.479583509587028, SCR: 3069.5665683207426

[I 2026-04-28 12:50:14,104] Trial 1 finished with value: 1876.7011407300224 and parameters: {'k_p1': 0.00042079886696066364, 'k_i1': 0.0004207053950287938, 'k_d1': 0.0001707396743152812, 'coef': 0.670721300885889}. Best is trial 0 with value: 3069.5665683207426.

CPC_REL: 123.69789896305221, rmse: 9.576799963561381, SCR: 1876.7011407300224

[I 2026-04-28 12:50:56,695] Trial 2 finished with value: 1566.9683110296605 and parameters: {'k_p1': 0.02537815508265665, 'k_i1': 0.06796578090758151, 'k_d1': 0.00012087541473056971, 'coef': 0.8424210519563055}. Best is trial 0 with value: 3069.5665683207426.

CPC_REL: 10.138914812001463, rmse: 12.527684505299963, SCR: 1566.9683110296605

[I 2026-04-28 12:52:09,256] Trial 3 finished with value: 5950.97691908025 and parameters: {'k_p1': 0.21368329072358744, 'k_i1': 0.0007068974950624604, 'k_d1': 0.000533703276260396, 'coef': 0.14962783074537747}. Best is trial 3 with value: 5950.97691908025.

CPC_REL: 6.313307967033146, rmse: 7.882273494176588, SCR: 5950.97691908025

[I 2026-04-28 12:52:55,992] Trial 4 finished with value: 5298.066615094176 and parameters: {'k_p1': 0.0016480446427978971, 'k_i1': 0.012561043700013555, 'k_d1': 0.005342937261279773, 'coef': 0.18962833227129433}. Best is trial 3 with value: 5950.97691908025.

CPC_REL: 229.93469778200634, rmse: 5.805418045015913, SCR: 5298.066615094176

[I 2026-04-28 12:53:56,278] Trial 5 finished with value: 5591.525600120887 and parameters: {'k_p1': 0.0280163515871626, 'k_i1': 0.0003613894271216529, 'k_d1': 0.0014742753159914669, 'coef': 0.22366500795357477}. Best is trial 3 with value: 5950.97691908025.

CPC_REL: 21.978332496367656, rmse: 6.064681322210586, SCR: 5591.525600120887

[I 2026-04-28 12:54:52,841] Trial 6 finished with value: 3634.4513128376807 and parameters: {'k_p1': 0.006672367170464205, 'k_i1': 0.13826232179369857, 'k_d1': 0.0006290644294586153, 'coef': 0.30953114978934915}. Best is trial 3 with value: 5950.97691908025.

CPC_REL: 20.537017539229314, rmse: 6.4286499498177045, SCR: 3634.4513128376807

[I 2026-04-28 12:55:42,648] Trial 7 finished with value: 6403.628629339121 and parameters: {'k_p1': 0.0234238498471129, 'k_i1': 0.00015339162591163628, 'k_d1': 0.02692646910086179, 'coef': 0.1454525594539987}. Best is trial 7 with value: 6403.628629339121.

CPC_REL: 45.16698361291875, rmse: 5.977953430053921, SCR: 6403.628629339121

[I 2026-04-28 12:56:18,617] Trial 8 finished with value: 2052.988980269228 and parameters: {'k_p1': 0.00018205657658407274, 'k_i1': 0.6245139574743068, 'k_d1': 0.7286653737491037, 'coef': 0.590754602820555}. Best is trial 7 with value: 6403.628629339121.

CPC_REL: 18.865163773828684, rmse: 10.070222017152542, SCR: 2052.988980269228

[I 2026-04-28 12:57:00,520] Trial 9 finished with value: 4067.3535396485736 and parameters: {'k_p1': 0.001653693718282443, 'k_i1': 0.00024586032763280086, 'k_d1': 0.054567254856014755, 'coef': 0.2630342003320024}. Best is trial 7 with value: 6403.628629339121.

CPC_REL: 210.91484201973546, rmse: 6.126432874123678, SCR: 4067.3535396485736

[I 2026-04-28 12:58:13,763] Trial 10 finished with value: 9444.879898161518 and parameters: {'k_p1': 0.645992478597833, 'k_i1': 0.002850432062787151, 'k_d1': 0.020788607320464402, 'coef': 0.10402554152175397}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 10.188891895909437, rmse: 6.283346174623299, SCR: 9444.879898161518

[I 2026-04-28 12:59:26,638] Trial 11 finished with value: 9438.061948002844 and parameters: {'k_p1': 0.7183428063433599, 'k_i1': 0.0025727052041819663, 'k_d1': 0.025194350392782144, 'coef': 0.10262527089572726}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 9.906328807314804, rmse: 6.071019945211007, SCR: 9438.061948002844

[I 2026-04-28 13:00:43,852] Trial 12 finished with value: 8508.01568322807 and parameters: {'k_p1': 0.7601737967676886, 'k_i1': 0.002930626723736014, 'k_d1': 0.009415145511616343, 'coef': 0.1019268624818704}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 7.430887702334861, rmse: 7.03726091292425, SCR: 8508.01568322807

[I 2026-04-28 13:01:37,577] Trial 13 finished with value: 7844.352797993077 and parameters: {'k_p1': 0.1883434758297889, 'k_i1': 0.0031636647883983523, 'k_d1': 0.3727934640385969, 'coef': 0.1024251365361687}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 12.70791668758357, rmse: 5.377516410784287, SCR: 7844.352797993077

[I 2026-04-28 13:02:34,223] Trial 14 finished with value: 7280.507679881341 and parameters: {'k_p1': 0.9520169142216904, 'k_i1': 0.007902399305479318, 'k_d1': 0.16749924043468287, 'coef': 0.13724546813689864}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 12.249213364899441, rmse: 6.3922709079175855, SCR: 7280.507679881341

[I 2026-04-28 13:03:15,327] Trial 15 finished with value: 2952.5882706403877 and parameters: {'k_p1': 0.1465133940160578, 'k_i1': 0.0014395592103981193, 'k_d1': 0.020075494236557426, 'coef': 0.4195813214037907}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 10.334401765584328, rmse: 7.714916833328381, SCR: 2952.5882706403877

[I 2026-04-28 13:04:24,813] Trial 16 finished with value: 8373.569572750408 and parameters: {'k_p1': 0.0637749874141854, 'k_i1': 0.015879173820604543, 'k_d1': 0.004045861382965444, 'coef': 0.12336897492580434}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 14.824242948586138, rmse: 5.8319505307535024, SCR: 8373.569572750408

[I 2026-04-28 13:05:29,253] Trial 17 finished with value: 6215.306967561177 and parameters: {'k_p1': 0.4811975111159744, 'k_i1': 0.03605084869732105, 'k_d1': 0.02387325945064319, 'coef': 0.18500322147116138}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.7849893866414615, rmse: 6.666070539407736, SCR: 6215.306967561177

[I 2026-04-28 13:06:39,931] Trial 18 finished with value: 7140.285788114887 and parameters: {'k_p1': 0.07631385437522864, 'k_i1': 0.0038620611663580592, 'k_d1': 0.002394177068357274, 'coef': 0.16745454815147645}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 14.626505620362288, rmse: 6.081317133652371, SCR: 7140.285788114887

[I 2026-04-28 13:07:33,577] Trial 19 finished with value: 7893.32295113201 and parameters: {'k_p1': 0.3489659465717498, 'k_i1': 0.001058335950825635, 'k_d1': 0.12478264836970224, 'coef': 0.11125456307001812}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 11.446479705777804, rmse: 5.165133888687944, SCR: 7893.32295113201

[I 2026-04-28 13:08:29,128] Trial 20 finished with value: 5140.1557391795595 and parameters: {'k_p1': 0.08917355794744274, 'k_i1': 0.005807074534696851, 'k_d1': 0.008734555018893362, 'coef': 0.22706063317193778}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.487318796029569, rmse: 6.511125975405854, SCR: 5140.1557391795595

[I 2026-04-28 13:09:46,355] Trial 21 finished with value: 8946.48348142501 and parameters: {'k_p1': 0.6410208732436814, 'k_i1': 0.002234527714289397, 'k_d1': 0.01041043060605382, 'coef': 0.10044358100528368}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 9.550068213772645, rmse: 5.712357892033034, SCR: 8946.48348142501

[I 2026-04-28 13:10:55,030] Trial 22 finished with value: 8179.666365100973 and parameters: {'k_p1': 0.43401655358591773, 'k_i1': 0.0017523429880530218, 'k_d1': 0.038259024040413994, 'coef': 0.12502312377246694}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 7.27883483095427, rmse: 6.337775970204267, SCR: 8179.666365100973

[I 2026-04-28 13:12:11,881] Trial 23 finished with value: 8909.995790501529 and parameters: {'k_p1': 0.9938764475637335, 'k_i1': 0.0213817638641051, 'k_d1': 0.01775557344760008, 'coef': 0.10194675114635428}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 9.975109212641907, rmse: 6.282328358436475, SCR: 8909.995790501529

[I 2026-04-28 13:13:25,914] Trial 24 finished with value: 8626.558450468812 and parameters: {'k_p1': 0.3070427449874034, 'k_i1': 0.000699831958850244, 'k_d1': 0.010339841184409004, 'coef': 0.12321319200643095}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.291739609695613, rmse: 5.819876993347675, SCR: 8626.558450468812

[I 2026-04-28 13:14:14,141] Trial 25 finished with value: 6130.532177568244 and parameters: {'k_p1': 0.12017783326943624, 'k_i1': 0.002323808734427691, 'k_d1': 0.05671551591482789, 'coef': 0.16074824069774885}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 12.840597390906847, rmse: 6.160330409131834, SCR: 6130.532177568244

[I 2026-04-28 13:15:05,399] Trial 26 finished with value: 6932.075928208351 and parameters: {'k_p1': 0.0398415401166964, 'k_i1': 0.006059407656779237, 'k_d1': 0.2929595811471912, 'coef': 0.12537930116868748}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 21.225631164966234, rmse: 5.506919495166847, SCR: 6932.075928208351

[I 2026-04-28 13:16:13,967] Trial 27 finished with value: 5348.058106699506 and parameters: {'k_p1': 0.5104446119851296, 'k_i1': 0.0009933632698005766, 'k_d1': 0.0018580778848353986, 'coef': 0.1833162415942495}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.427769775441085, rmse: 7.399381924624012, SCR: 5348.058106699506

[I 2026-04-28 13:16:58,734] Trial 28 finished with value: 4765.632636798893 and parameters: {'k_p1': 0.010767516438372038, 'k_i1': 0.046899671234917506, 'k_d1': 0.010541476531996155, 'coef': 0.21896872580247692}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 51.21465493722361, rmse: 5.79054287947891, SCR: 4765.632636798893

[I 2026-04-28 13:17:37,902] Trial 29 finished with value: 3026.108570410659 and parameters: {'k_p1': 0.26127154548580056, 'k_i1': 0.005210661377064373, 'k_d1': 0.09016949802023566, 'coef': 0.38580426035792303}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 16.066490747153242, rmse: 7.39564803919737, SCR: 3026.108570410659

[I 2026-04-28 13:18:30,434] Trial 30 finished with value: 2644.3075550442973 and parameters: {'k_p1': 0.6203114426286812, 'k_i1': 0.00011170865957782298, 'k_d1': 0.005068938723376863, 'coef': 0.48757307313827936}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 5.585912168752023, rmse: 9.248508249855574, SCR: 2644.3075550442973

[I 2026-04-28 13:19:47,449] Trial 31 finished with value: 8950.455119957624 and parameters: {'k_p1': 0.9605575563254296, 'k_i1': 0.020682300373577905, 'k_d1': 0.01862477259433817, 'coef': 0.1019458537883918}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 10.110377263692904, rmse: 6.097208594796058, SCR: 8950.455119957624

[I 2026-04-28 13:20:59,369] Trial 32 finished with value: 8684.036355298857 and parameters: {'k_p1': 0.9948274578423025, 'k_i1': 0.00980394859362697, 'k_d1': 0.039607621206998254, 'coef': 0.11871889827862589}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.604624792878548, rmse: 6.22185226470711, SCR: 8684.036355298857

[I 2026-04-28 13:22:08,910] Trial 33 finished with value: 7651.202653994351 and parameters: {'k_p1': 0.35202483614543884, 'k_i1': 0.1422902262049457, 'k_d1': 0.015499831449946332, 'coef': 0.13542052343031605}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 7.00764535082928, rmse: 6.469515537758426, SCR: 7651.202653994351

[I 2026-04-28 13:23:25,067] Trial 34 finished with value: 9140.610661122413 and parameters: {'k_p1': 0.16896194732789221, 'k_i1': 0.02213785984566302, 'k_d1': 0.0030693715289102524, 'coef': 0.10002863845738566}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.724475389803274, rmse: 6.416143607268347, SCR: 9140.610661122413

[I 2026-04-28 13:24:04,966] Trial 35 finished with value: 1628.5359991828216 and parameters: {'k_p1': 0.20882240770739796, 'k_i1': 0.0313016149971622, 'k_d1': 0.005094026751695044, 'coef': 0.8489604652317392}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 10.788356073865653, rmse: 13.414937833974182, SCR: 1628.5359991828216

[I 2026-04-28 13:25:18,678] Trial 36 finished with value: 6616.6475291378365 and parameters: {'k_p1': 0.2526204652054459, 'k_i1': 0.09095705604607605, 'k_d1': 0.00047142503443883436, 'coef': 0.11059129602460488}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.4307114624263955, rmse: 7.587341907782378, SCR: 6616.6475291378365

[I 2026-04-28 13:26:31,378] Trial 37 finished with value: 6558.069058107418 and parameters: {'k_p1': 0.12566838818311013, 'k_i1': 0.021476225720921137, 'k_d1': 0.0013023274074245156, 'coef': 0.15699610820638998}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.39318736586093, rmse: 6.799467651238042, SCR: 6558.069058107418

[I 2026-04-28 13:27:34,938] Trial 38 finished with value: 6484.081662568323 and parameters: {'k_p1': 0.004553167349901106, 'k_i1': 0.27025680573738087, 'k_d1': 0.0030557974755982846, 'coef': 0.13862393263257358}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 21.82028085041035, rmse: 5.926308602006227, SCR: 6484.081662568323

[I 2026-04-28 13:28:12,495] Trial 39 finished with value: 1757.0394947302902 and parameters: {'k_p1': 0.013136717880942806, 'k_i1': 0.011320182826918402, 'k_d1': 0.0010519588736547627, 'coef': 0.7296325389342113}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 18.55776091285107, rmse: 10.893774100208532, SCR: 1757.0394947302902

[I 2026-04-28 13:29:04,338] Trial 40 finished with value: 7408.875657236752 and parameters: {'k_p1': 0.0004115208326500335, 'k_i1': 0.06056985429670341, 'k_d1': 0.03454664490535395, 'coef': 0.11291671174368577}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 206.64708199623394, rmse: 4.625961818491686, SCR: 7408.875657236752

[I 2026-04-28 13:30:19,059] Trial 41 finished with value: 8601.942377692889 and parameters: {'k_p1': 0.5327562284570232, 'k_i1': 0.0005226670788250656, 'k_d1': 0.007062706686916539, 'coef': 0.10016495391380029}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.937847612405633, rmse: 5.886301792564028, SCR: 8601.942377692889

[I 2026-04-28 13:31:32,045] Trial 42 finished with value: 8733.847896207502 and parameters: {'k_p1': 0.6554337502138037, 'k_i1': 0.0018430495957568644, 'k_d1': 0.01408206058520708, 'coef': 0.11152723635194657}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.777510224262956, rmse: 5.590368066370954, SCR: 8733.847896207502

[I 2026-04-28 13:32:32,889] Trial 43 finished with value: 7499.878100637203 and parameters: {'k_p1': 0.6971748293145849, 'k_i1': 0.01786449961226121, 'k_d1': 0.0671941887291879, 'coef': 0.14297565403309087}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 6.909684753779786, rmse: 6.697606945765828, SCR: 7499.878100637203

[I 2026-04-28 13:33:39,157] Trial 44 finished with value: 8069.748153253094 and parameters: {'k_p1': 0.4108373189981391, 'k_i1': 0.003579949219577456, 'k_d1': 0.02490472699129001, 'coef': 0.12924038910611607}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.165539583459314, rmse: 6.506374233574373, SCR: 8069.748153253094

[I 2026-04-28 13:34:51,539] Trial 45 finished with value: 7036.608896960826 and parameters: {'k_p1': 0.1698910763030908, 'k_i1': 0.006811024943978107, 'k_d1': 0.0002145470999887603, 'coef': 0.10014557426317787}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 7.532181132725286, rmse: 6.662126642279589, SCR: 7036.608896960826

[I 2026-04-28 13:35:44,845] Trial 46 finished with value: 4364.165924109766 and parameters: {'k_p1': 0.04905281676409446, 'k_i1': 0.0002687389971478708, 'k_d1': 0.00299739277504678, 'coef': 0.29015817059438986}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 13.908187338784812, rmse: 7.075712789614118, SCR: 4364.165924109766

[I 2026-04-28 13:36:57,487] Trial 47 finished with value: 8416.286177507309 and parameters: {'k_p1': 0.7184492294382164, 'k_i1': 0.004077416336327225, 'k_d1': 0.013262418663697128, 'coef': 0.11367895567037867}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 8.421862018522612, rmse: 6.287553774282662, SCR: 8416.286177507309

[I 2026-04-28 13:37:45,672] Trial 48 finished with value: 6394.69716286811 and parameters: {'k_p1': 0.01916014652676797, 'k_i1': 0.0012597141766439582, 'k_d1': 0.0067383421112601075, 'coef': 0.153681446569442}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 46.06792020497, rmse: 5.7695077992672275, SCR: 6394.69716286811

[I 2026-04-28 13:38:37,325] Trial 49 finished with value: 7360.455961626043 and parameters: {'k_p1': 0.0011696766705514483, 'k_i1': 0.0026042641191525106, 'k_d1': 0.1011676336366731, 'coef': 0.11248386313252527}. Best is trial 10 with value: 9444.879898161518.

CPC_REL: 377.7819456718299, rmse: 4.098336461781693, SCR: 7360.455961626043
Best trial:
Value: 9444.879898161518
Params:
    k_p1: 0.645992478597833
    k_i1: 0.002850432062787151
    k_d1: 0.020788607320464402
    coef: 0.10402554152175397

[I 2026-04-28 13:39:52,211] A new study created in memory with name: no-name-7b71214e-dbbb-48d2-807c-63937bd67232

CPC_REL: 10.94062030818801, rmse: 7.7223390870045145, SCR: 8623.413929558174
=== MPID | metric=SCR | auction_mode=FPA ===

[I 2026-04-28 13:54:53,033] Trial 1 finished with value: 13104.875884407451 and parameters: {'k_p1': 0.00043835665031224214, 'k_p2': 0.0005090510955995888, 'k_i1': 0.0021505250315766314, 'k_i2': 0.043522998264438596, 'k_d1': 0.02287536914170614, 'k_d2': 0.0001539570133764369, 'alpha': 0.7857842407699304, 'beta': 0.20848363836327538, 'coef': 0.8635431810516816, 'lower_clip': 0.31924134290829065, 'upper_clip': 6.724553776818991, 'bid_factor': 0.7970490015650754}. Best is trial 1 with value: 13104.875884407451.

CPC_REL: 615.7855641358204, rmse: 1.4225977631249695, SCR: 13104.875884407451

[I 2026-04-28 13:55:14,888] Trial 0 finished with value: 13234.192934739342 and parameters: {'k_p1': 0.01172177650670799, 'k_p2': 0.029280710478451693, 'k_i1': 0.00924600450634432, 'k_i2': 0.0010469573780770012, 'k_d1': 0.0487971934918617, 'k_d2': 0.001999505246001453, 'alpha': 0.7027253938954523, 'beta': 0.32467694344851145, 'coef': 0.6533188765213468, 'lower_clip': 0.20058395768798884, 'upper_clip': 2.4302791453308337, 'bid_factor': 18.906360205735822}. Best is trial 0 with value: 13234.192934739342.

CPC_REL: 748.1591390846964, rmse: 1.335424519039026, SCR: 13234.192934739342

[I 2026-04-28 13:55:20,669] Trial 5 finished with value: 13324.737928222294 and parameters: {'k_p1': 0.5296051294321172, 'k_p2': 0.2182767460735082, 'k_i1': 0.000491101095106486, 'k_i2': 0.0009563176983264481, 'k_d1': 0.014981339164783595, 'k_d2': 0.18201187566372387, 'alpha': 0.6260255340666225, 'beta': 0.13844813974844125, 'coef': 0.2405565792884254, 'lower_clip': 0.371156185605606, 'upper_clip': 5.370407550610196, 'bid_factor': 6.21671459894426}. Best is trial 5 with value: 13324.737928222294.

CPC_REL: 1121.9515274513778, rmse: 1.2324814077040824, SCR: 13324.737928222294

[I 2026-04-28 13:55:22,421] Trial 2 finished with value: 13280.281802938907 and parameters: {'k_p1': 0.00044702156410904114, 'k_p2': 0.0007248562646385452, 'k_i1': 0.008769528010784825, 'k_i2': 0.4880949265548948, 'k_d1': 0.0004883815873776835, 'k_d2': 0.0005391644693506509, 'alpha': 0.27000219595556635, 'beta': 0.3610258670445844, 'coef': 0.15038515730202012, 'lower_clip': 0.2445780563805068, 'upper_clip': 1.5251407542217408, 'bid_factor': 13.126505217470186}. Best is trial 5 with value: 13324.737928222294.

CPC_REL: 1168.674055940353, rmse: 1.23210193068163, SCR: 13280.281802938907

[I 2026-04-28 13:55:22,887] Trial 3 finished with value: 13253.0394377461 and parameters: {'k_p1': 0.030168377622772923, 'k_p2': 0.8326162505197154, 'k_i1': 0.1290667700265531, 'k_i2': 0.005672856973780037, 'k_d1': 0.006263659812785274, 'k_d2': 0.007715014242135929, 'alpha': 0.12950055019138496, 'beta': 0.27857679492177156, 'coef': 0.13664028122110686, 'lower_clip': 0.5214053058716669, 'upper_clip': 3.3527594105519944, 'bid_factor': 6.39592451079116}. Best is trial 5 with value: 13324.737928222294.

CPC_REL: 1168.6726786059953, rmse: 1.2324923126049898, SCR: 13253.0394377461

[I 2026-04-28 13:55:24,407] Trial 4 finished with value: 13276.62477149877 and parameters: {'k_p1': 0.01253237936694982, 'k_p2': 0.03705151746912051, 'k_i1': 0.0034945840314561114, 'k_i2': 0.05164710291804283, 'k_d1': 0.007730336989610508, 'k_d2': 0.0010567289100157215, 'alpha': 0.2632610889479606, 'beta': 0.47800329018782, 'coef': 0.15995017306842238, 'lower_clip': 0.2823108861446943, 'upper_clip': 1.9321797544993657, 'bid_factor': 4.807722999828328}. Best is trial 5 with value: 13324.737928222294.

CPC_REL: 1168.674558326222, rmse: 1.2320437900668708, SCR: 13276.62477149877

[I 2026-04-28 14:09:22,856] Trial 6 finished with value: 13338.135301762275 and parameters: {'k_p1': 0.00017659443700703835, 'k_p2': 0.0011840331712717049, 'k_i1': 0.00017825794387169204, 'k_i2': 0.00023111612156194412, 'k_d1': 0.007671714829150809, 'k_d2': 0.030475790900313684, 'alpha': 0.12773940398790068, 'beta': 0.614870294889325, 'coef': 0.21805405355405905, 'lower_clip': 0.8164204221439988, 'upper_clip': 2.731809260425576, 'bid_factor': 9.23443559820401}. Best is trial 6 with value: 13338.135301762275.

CPC_REL: 1121.9502968932718, rmse: 1.2316018694069852, SCR: 13338.135301762275

[I 2026-04-28 14:10:00,144] Trial 7 finished with value: 13231.895964215186 and parameters: {'k_p1': 0.016183184396951288, 'k_p2': 0.00561006478837977, 'k_i1': 0.04049419161060863, 'k_i2': 0.0001668928210412857, 'k_d1': 0.00023419992608979007, 'k_d2': 0.6555949948766765, 'alpha': 0.11954273500242148, 'beta': 0.33890847045832095, 'coef': 0.11599679066854453, 'lower_clip': 0.32048497898907524, 'upper_clip': 8.467736858842766, 'bid_factor': 7.918821763064159}. Best is trial 6 with value: 13338.135301762275.

CPC_REL: 1168.6714512662802, rmse: 1.233202087749467, SCR: 13231.895964215186

[I 2026-04-28 14:10:08,110] Trial 8 finished with value: 13364.012725998906 and parameters: {'k_p1': 0.00011296234410694694, 'k_p2': 0.05807830443577337, 'k_i1': 0.13563804849492989, 'k_i2': 0.21406709239799962, 'k_d1': 0.0004344793777644934, 'k_d2': 0.2360733990020912, 'alpha': 0.37131642390238184, 'beta': 0.48271891959997215, 'coef': 0.3702032646065846, 'lower_clip': 0.3178792128764501, 'upper_clip': 7.558351254878056, 'bid_factor': 8.179828120431887}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1012.9291498375595, rmse: 1.245123661280885, SCR: 13364.012725998906

[I 2026-04-28 14:10:16,977] Trial 10 finished with value: 13332.44449496995 and parameters: {'k_p1': 0.15881042295628267, 'k_p2': 0.0012722198758460302, 'k_i1': 0.0018064687388712403, 'k_i2': 0.015601581833290721, 'k_d1': 0.839835021313592, 'k_d2': 0.00875583664514559, 'alpha': 0.13719733601229406, 'beta': 0.823118360743574, 'coef': 0.34627215755725144, 'lower_clip': 0.34658984538513987, 'upper_clip': 5.184370570453169, 'bid_factor': 9.575512037521488}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1051.866831832994, rmse: 1.2403820972116009, SCR: 13332.44449496995

[I 2026-04-28 14:10:19,829] Trial 9 finished with value: 13254.00583309917 and parameters: {'k_p1': 0.009650022025924366, 'k_p2': 0.0030555292370807183, 'k_i1': 0.02043040557387915, 'k_i2': 0.0004402036100465082, 'k_d1': 0.40480692230591414, 'k_d2': 0.004544120893038571, 'alpha': 0.2297754931355269, 'beta': 0.14624105218447572, 'coef': 0.11454113576237628, 'lower_clip': 0.26180719107820727, 'upper_clip': 1.5436396325921666, 'bid_factor': 2.850271487707624}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1168.6699350996673, rmse: 1.2318016703933123, SCR: 13254.00583309917

[I 2026-04-28 14:10:20,761] Trial 11 finished with value: 13277.48777460348 and parameters: {'k_p1': 0.005566105374513407, 'k_p2': 0.00017745805806256422, 'k_i1': 0.045122690438658096, 'k_i2': 0.07727760249058103, 'k_d1': 0.04586131292834372, 'k_d2': 0.0012837340308208191, 'alpha': 0.12490807019748701, 'beta': 0.6632173276281526, 'coef': 0.15769297664062729, 'lower_clip': 0.13232329031388942, 'upper_clip': 2.3565742214267917, 'bid_factor': 6.58614924335746}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1168.6744310450233, rmse: 1.2320578168749103, SCR: 13277.48777460348

[I 2026-04-28 14:23:36,634] Trial 12 finished with value: 13275.534308116552 and parameters: {'k_p1': 0.0009227306674482734, 'k_p2': 0.006871117586996879, 'k_i1': 0.022770786964543006, 'k_i2': 0.0001940112731112111, 'k_d1': 0.00635003978556958, 'k_d2': 0.00011181665326519673, 'alpha': 0.5402127425478863, 'beta': 0.39826478276580907, 'coef': 0.653905118722725, 'lower_clip': 0.3458597040852698, 'upper_clip': 2.616916539579211, 'bid_factor': 5.327748030660458}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 748.1610960108057, rmse: 1.3335343172694565, SCR: 13275.534308116552

[I 2026-04-28 14:24:42,211] Trial 13 finished with value: 13357.327368345857 and parameters: {'k_p1': 0.032416838964223295, 'k_p2': 0.016087241574298552, 'k_i1': 0.3007985071914274, 'k_i2': 0.1051678550229667, 'k_d1': 0.001408047673069585, 'k_d2': 0.5952578918095058, 'alpha': 0.2011906540116826, 'beta': 0.8157297347675169, 'coef': 0.2664241487898805, 'lower_clip': 0.12897667537382884, 'upper_clip': 2.765050719654666, 'bid_factor': 3.9752982240531756}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1090.801527277104, rmse: 1.2344149158348576, SCR: 13357.327368345857

[I 2026-04-28 14:24:50,435] Trial 14 finished with value: 13341.600622823833 and parameters: {'k_p1': 0.3970008939565658, 'k_p2': 0.3713120972687746, 'k_i1': 0.0024539956785534413, 'k_i2': 0.0009225524985355548, 'k_d1': 0.3642744142665337, 'k_d2': 0.8102798905856937, 'alpha': 0.2560174445712164, 'beta': 0.2048955423629928, 'coef': 0.21218071636289873, 'lower_clip': 0.1695342151460052, 'upper_clip': 5.993403047711223, 'bid_factor': 4.867034741293274}. Best is trial 8 with value: 13364.012725998906.

CPC_REL: 1121.9499081498761, rmse: 1.2314051302231925, SCR: 13341.600622823833

[I 2026-04-28 14:24:58,618] Trial 15 finished with value: 13344.825641342164 and parameters: {'k_p1': 0.002584756488396902, 'k_p2': 0.13597418331026145, 'k_i1': 0.8865972683127427, 'k_i2': 0.9995107067573453, 'k_d1': 0.0010779618151608892, 'k_d2': 0.09278315306073512, 'alpha': 0.421141861909952, 'beta': 0.8986236736886165, 'coef': 0.4513845439576949, 'lower_clip': 0.1063696447933762, 'upper_clip': 8.573880330848919, 'bid_factor': 1.8216329375254259}. Best is trial 8 with value: 13364.012725998906.
[I 2026-04-28 14:24:58,693] Trial 17 finished with value: 13736.046734752576 and parameters: {'k_p1': 0.00010711963221447478, 'k_p2': 0.026378736542662366, 'k_i1': 0.29046491650716083, 'k_i2': 0.9448661476264385, 'k_d1': 0.0017126185131561165, 'k_d2': 0.05894957367173661, 'alpha': 0.43414108733497436, 'beta': 0.5374251089031703, 'coef': 0.3732450776864588, 'lower_clip': 0.8563282014199454, 'upper_clip': 3.577578034895007, 'bid_factor': 2.389680578984107}. Best is trial 17 with value: 13736.046734752576.

CPC_REL: 958.4197295682499, rmse: 1.2657374661426586, SCR: 13344.825641342164
CPC_REL: 693.7020594657217, rmse: 1.2735164616251649, SCR: 13736.046734752576

[I 2026-04-28 14:25:03,538] Trial 16 finished with value: 13374.095002555827 and parameters: {'k_p1': 0.00011157390559771666, 'k_p2': 0.00011579364844931507, 'k_i1': 0.9181610182325584, 'k_i2': 0.9091219675617174, 'k_d1': 0.0012431626828382598, 'k_d2': 0.06651211989845471, 'alpha': 0.4427878432751914, 'beta': 0.6806424337111152, 'coef': 0.3558222571197556, 'lower_clip': 0.10605197345432993, 'upper_clip': 3.6153674095078423, 'bid_factor': 2.249173045668708}. Best is trial 17 with value: 13736.046734752576.

CPC_REL: 1012.9281029862495, rmse: 1.243409717976605, SCR: 13374.095002555827

[I 2026-04-28 14:38:07,255] Trial 18 finished with value: 13749.05352506257 and parameters: {'k_p1': 0.00014549272611370624, 'k_p2': 0.03463406672619386, 'k_i1': 0.8321215217978918, 'k_i2': 0.739647570438475, 'k_d1': 0.001003133452129965, 'k_d2': 0.05933102545526528, 'alpha': 0.38904142341484427, 'beta': 0.5977024934261528, 'coef': 0.3292145715242233, 'lower_clip': 0.877442043160268, 'upper_clip': 3.640062424948245, 'bid_factor': 2.5964398606984216}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 779.3414525989965, rmse: 1.2485471704731614, SCR: 13749.05352506257

[I 2026-04-28 14:39:38,609] Trial 19 finished with value: 13329.083590725772 and parameters: {'k_p1': 0.08514170707956915, 'k_p2': 0.036396903254521495, 'k_i1': 0.7342680389470179, 'k_i2': 0.45580095454897435, 'k_d1': 0.0010884636494769562, 'k_d2': 0.07165001739357972, 'alpha': 0.4166941778806778, 'beta': 0.8316423350422377, 'coef': 0.3512078890450644, 'lower_clip': 0.10441265941810951, 'upper_clip': 4.173424258880696, 'bid_factor': 2.1043967610973517}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 1051.867201863429, rmse: 1.2408724703007705, SCR: 13329.083590725772

[I 2026-04-28 14:39:51,304] Trial 20 finished with value: 13356.156075744635 and parameters: {'k_p1': 0.0020179573318334977, 'k_p2': 0.04221591802431907, 'k_i1': 0.7927987350378544, 'k_i2': 0.9854256413600909, 'k_d1': 0.0011031620003473452, 'k_d2': 0.0997267229879491, 'alpha': 0.3946954663864177, 'beta': 0.8078597889507684, 'coef': 0.3813676837700293, 'lower_clip': 0.10160283292398513, 'upper_clip': 4.062017646316952, 'bid_factor': 2.2589481798762208}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 1012.9299418642588, rmse: 1.2463960515526835, SCR: 13356.156075744635

[I 2026-04-28 14:39:55,842] Trial 22 finished with value: 13720.711239546154 and parameters: {'k_p1': 0.00010109029712863751, 'k_p2': 0.07850134774225645, 'k_i1': 0.18047588894237623, 'k_i2': 0.23099037400452976, 'k_d1': 0.00014521480620175562, 'k_d2': 0.04339162308747394, 'alpha': 0.3846574334199241, 'beta': 0.5207805432800406, 'coef': 0.37703631406642163, 'lower_clip': 0.8533220614668248, 'upper_clip': 4.469618030153294, 'bid_factor': 1.823942783502243}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 693.702241372062, rmse: 1.2748248434145957, SCR: 13720.711239546154

[I 2026-04-28 14:40:01,772] Trial 21 finished with value: 13375.197021792066 and parameters: {'k_p1': 0.039388920646163395, 'k_p2': 0.03189456976202383, 'k_i1': 0.41386669689047667, 'k_i2': 0.25023109612691896, 'k_d1': 0.00010729814822154451, 'k_d2': 0.16183879055266662, 'alpha': 0.17804864462355788, 'beta': 0.540749278751378, 'coef': 0.35425037533318543, 'lower_clip': 0.5166647049445255, 'upper_clip': 4.108917050796114, 'bid_factor': 2.238282008314086}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 1012.9279969468242, rmse: 1.243218019571638, SCR: 13375.197021792066

[I 2026-04-28 14:40:05,095] Trial 23 finished with value: 13553.880300798832 and parameters: {'k_p1': 0.001169263492323799, 'k_p2': 0.00014056756102009035, 'k_i1': 0.6798018373469632, 'k_i2': 0.3529653887161725, 'k_d1': 0.00010525923876164296, 'k_d2': 0.031290601523985745, 'alpha': 0.43453986221572904, 'beta': 0.5665964331524475, 'coef': 0.4245186870692811, 'lower_clip': 0.7533105363020827, 'upper_clip': 4.283961526258465, 'bid_factor': 1.4298440621799826}. Best is trial 18 with value: 13749.05352506257.

CPC_REL: 849.4144885783819, rmse: 1.2924484095390418, SCR: 13553.880300798832

[I 2026-04-28 14:52:13,240] Trial 24 finished with value: 13967.490247099708 and parameters: {'k_p1': 0.0016741451758430822, 'k_p2': 0.063838887742, 'k_i1': 0.2830855351209029, 'k_i2': 0.329624194368249, 'k_d1': 0.0027526276870799976, 'k_d2': 0.03260005215949148, 'alpha': 0.33653108273753296, 'beta': 0.10348157705172968, 'coef': 0.4884265384567238, 'lower_clip': 0.8912113767226837, 'upper_clip': 4.3343698919723295, 'bid_factor': 1.2327572015995283}. Best is trial 24 with value: 13967.490247099708.

CPC_REL: 320.20155866038124, rmse: 1.3978182897472016, SCR: 13967.490247099708

[I 2026-04-28 14:54:00,631] Trial 25 finished with value: 13987.69098398148 and parameters: {'k_p1': 0.001580550809860663, 'k_p2': 0.07748261476306627, 'k_i1': 0.20648462123991718, 'k_i2': 0.015378356463679776, 'k_d1': 0.0001244195748456774, 'k_d2': 0.01717121082588407, 'alpha': 0.34193459326742587, 'beta': 0.5093359800237278, 'coef': 0.4748021421210206, 'lower_clip': 0.8953241481379589, 'upper_clip': 4.46793596656986, 'bid_factor': 1.161110905612604}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 335.7633181152683, rmse: 1.3928966518854755, SCR: 13987.69098398148

[I 2026-04-28 14:54:22,328] Trial 26 finished with value: 13397.188016732678 and parameters: {'k_p1': 0.0002675231069439767, 'k_p2': 0.00013955788201309847, 'k_i1': 0.2641957458220485, 'k_i2': 0.24946588689315266, 'k_d1': 0.00012149888521612727, 'k_d2': 0.02621091095081287, 'alpha': 0.5345447679824494, 'beta': 0.6050455775497928, 'coef': 0.5829588089711044, 'lower_clip': 0.7890937048949699, 'upper_clip': 3.4174947529922366, 'bid_factor': 1.2673678498889838}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 405.69192329960083, rmse: 1.4144518357577656, SCR: 13397.188016732678

[I 2026-04-28 14:54:26,996] Trial 28 finished with value: 13952.406909517042 and parameters: {'k_p1': 0.00028674313027519867, 'k_p2': 0.11833220884813714, 'k_i1': 0.1716110000148674, 'k_i2': 0.22046420228578953, 'k_d1': 0.0027469763932421796, 'k_d2': 0.024678826139070627, 'alpha': 0.3212614373038793, 'beta': 0.4241035683906201, 'coef': 0.487797463211397, 'lower_clip': 0.8904637955920225, 'upper_clip': 4.8895287543937895, 'bid_factor': 1.2461581745432484}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 320.1965340861528, rmse: 1.3976551005820952, SCR: 13952.406909517042

[I 2026-04-28 14:54:36,924] Trial 27 finished with value: 13595.408699023763 and parameters: {'k_p1': 0.0003303773225842835, 'k_p2': 0.10070283571760284, 'k_i1': 0.23805496664094405, 'k_i2': 0.24455302454779343, 'k_d1': 0.00011717275086315783, 'k_d2': 0.015818692377344654, 'alpha': 0.31809688808066605, 'beta': 0.4828748605226134, 'coef': 0.48600975443205635, 'lower_clip': 0.8319478421444517, 'upper_clip': 4.434911243110494, 'bid_factor': 1.1992213527068711}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 444.600854677956, rmse: 1.3619562753598693, SCR: 13595.408699023763

[I 2026-04-28 14:55:08,466] Trial 29 finished with value: 13495.112876167335 and parameters: {'k_p1': 0.00028651965942069123, 'k_p2': 0.10770332151984108, 'k_i1': 0.17943429926951387, 'k_i2': 0.1725799736534368, 'k_d1': 0.002365918216164403, 'k_d2': 0.02307708680643738, 'alpha': 0.34528560550031784, 'beta': 0.429733117173933, 'coef': 0.48055651681968925, 'lower_clip': 0.6533007993142926, 'upper_clip': 3.05849263284422, 'bid_factor': 1.1094800142769123}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 864.982495849089, rmse: 1.2995374606031826, SCR: 13495.112876167335

[I 2026-04-28 15:06:50,476] Trial 30 finished with value: 13390.058787228269 and parameters: {'k_p1': 0.00033204823302929653, 'k_p2': 0.014123623049238023, 'k_i1': 0.08601341590898152, 'k_i2': 0.01976102058635515, 'k_d1': 0.003125708308621526, 'k_d2': 0.018274089986240565, 'alpha': 0.32561806653370845, 'beta': 0.10032626085565026, 'coef': 0.5589101122240686, 'lower_clip': 0.6516830534900739, 'upper_clip': 3.260940941637901, 'bid_factor': 0.8876684860191801}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 724.81916923587, rmse: 1.339297045905468, SCR: 13390.058787228269

[I 2026-04-28 15:08:57,440] Trial 31 finished with value: 13406.319301632675 and parameters: {'k_p1': 0.00033728631025426814, 'k_p2': 0.11351125822072543, 'k_i1': 0.0732058857524715, 'k_i2': 0.006777869625817424, 'k_d1': 0.0032835652541962673, 'k_d2': 0.017105083153573033, 'alpha': 0.33561729894929077, 'beta': 0.10251490668456356, 'coef': 0.5339229550780112, 'lower_clip': 0.6477045474613727, 'upper_clip': 3.0457009419820165, 'bid_factor': 0.9670724198112124}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 748.1737923765459, rmse: 1.3223347218926695, SCR: 13406.319301632675

[I 2026-04-28 15:09:22,464] Trial 32 finished with value: 13437.893399586877 and parameters: {'k_p1': 0.0038508263286031897, 'k_p2': 0.013308648155538854, 'k_i1': 0.06961181505132095, 'k_i2': 0.012263236777604665, 'k_d1': 0.0003552716633931078, 'k_d2': 0.0035792524317464947, 'alpha': 0.3296101428837659, 'beta': 0.25646337264548025, 'coef': 0.5134653885111835, 'lower_clip': 0.6404477198529787, 'upper_clip': 3.108963907930476, 'bid_factor': 0.7517072553385236}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 755.9549168542751, rmse: 1.31465622444614, SCR: 13437.893399586877

[I 2026-04-28 15:09:27,550] Trial 33 finished with value: 13437.605140957769 and parameters: {'k_p1': 0.003743420970474912, 'k_p2': 0.10961955714891804, 'k_i1': 0.07583228935475808, 'k_i2': 0.007563923380855756, 'k_d1': 0.003676040751347504, 'k_d2': 0.016445698058898884, 'alpha': 0.31523299349243233, 'beta': 0.10031005936638822, 'coef': 0.512803205773464, 'lower_clip': 0.6413316163481404, 'upper_clip': 4.99242897022805, 'bid_factor': 0.5014814013031129}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 755.9549305769523, rmse: 1.3145266116812047, SCR: 13437.605140957769

[I 2026-04-28 15:09:39,584] Trial 34 finished with value: 13464.371506939091 and parameters: {'k_p1': 0.003341861711056511, 'k_p2': 0.35489914699895403, 'k_i1': 0.0794248204400786, 'k_i2': 0.004695206020467109, 'k_d1': 0.0028001482447775746, 'k_d2': 0.0034579941827328634, 'alpha': 0.31328151123945486, 'beta': 0.2724773793801545, 'coef': 0.5439951350978939, 'lower_clip': 0.663599212675373, 'upper_clip': 5.265464607558988, 'bid_factor': 0.5211432402310208}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 693.6670994429267, rmse: 1.3371541671514011, SCR: 13464.371506939091

[I 2026-04-28 15:10:10,512] Trial 35 finished with value: 13370.865528327426 and parameters: {'k_p1': 0.0036840887412293265, 'k_p2': 0.37126959553930855, 'k_i1': 0.07467571473575764, 'k_i2': 0.005035695058035695, 'k_d1': 0.003280757327047642, 'k_d2': 0.0042745243558099996, 'alpha': 0.3078061957387516, 'beta': 0.11173402792717112, 'coef': 0.5890201778421407, 'lower_clip': 0.6352399227472291, 'upper_clip': 5.308016134080214, 'bid_factor': 0.6201527465177293}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 693.6707775332113, rmse: 1.3513110205999557, SCR: 13370.865528327426

[I 2026-04-28 15:21:28,757] Trial 36 finished with value: 12921.522495739639 and parameters: {'k_p1': 0.0009043978599385667, 'k_p2': 0.20223423040467833, 'k_i1': 0.07146645473931894, 'k_i2': 0.0030117718268581855, 'k_d1': 0.0005469128444306337, 'k_d2': 0.004225451510348548, 'alpha': 0.5404628667616176, 'beta': 0.2863272184100734, 'coef': 0.8354153191951857, 'lower_clip': 0.6655139866324248, 'upper_clip': 4.85958019999826, 'bid_factor': 0.6107831612077453}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 351.1601072413695, rmse: 1.533179241169794, SCR: 12921.522495739639

[I 2026-04-28 15:24:03,754] Trial 37 finished with value: 13296.902645111726 and parameters: {'k_p1': 0.0006542728240876902, 'k_p2': 0.23960059034539713, 'k_i1': 0.41783625363006593, 'k_i2': 0.0037174637617922507, 'k_d1': 0.0004848063633976946, 'k_d2': 0.004159238854721624, 'alpha': 0.2896828479869718, 'beta': 0.2704740692829309, 'coef': 0.6757617934148102, 'lower_clip': 0.5327477709802517, 'upper_clip': 5.504792960344233, 'bid_factor': 0.5638798191894069}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 662.5134334434663, rmse: 1.371759885477908, SCR: 13296.902645111726

[I 2026-04-28 15:24:32,489] Trial 38 finished with value: 13279.377562172907 and parameters: {'k_p1': 0.0008162952737632743, 'k_p2': 0.26141335634908625, 'k_i1': 0.4901123017700106, 'k_i2': 0.0035072093950776957, 'k_d1': 0.0006212165425019746, 'k_d2': 0.004322795863694736, 'alpha': 0.5134026493943646, 'beta': 0.3900269337546699, 'coef': 0.676204844499254, 'lower_clip': 0.510713044709814, 'upper_clip': 5.354025717951297, 'bid_factor': 0.5388876788815312}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 678.0852890589246, rmse: 1.3647849199956519, SCR: 13279.377562172907

[I 2026-04-28 15:24:33,177] Trial 39 finished with value: 12967.013468497424 and parameters: {'k_p1': 0.000713627826543725, 'k_p2': 0.3135190314212477, 'k_i1': 0.4638729023928207, 'k_i2': 0.02999760672082722, 'k_d1': 0.0005302758643147333, 'k_d2': 0.0055351600795586235, 'alpha': 0.5168301331665489, 'beta': 0.3934871057315528, 'coef': 0.8619279271971753, 'lower_clip': 0.5105358086083769, 'upper_clip': 6.3710675562017665, 'bid_factor': 0.5499545936175532}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 530.1511849920302, rmse: 1.4707587426513953, SCR: 12967.013468497424

[I 2026-04-28 15:24:49,841] Trial 40 finished with value: 13040.888386560988 and parameters: {'k_p1': 0.0007906814201685651, 'k_p2': 0.706796337062899, 'k_i1': 0.47634685207664834, 'k_i2': 0.003238221421384601, 'k_d1': 0.0006760155078405982, 'k_d2': 0.007241924803468848, 'alpha': 0.48884422818373613, 'beta': 0.4067338270959486, 'coef': 0.8039221981171384, 'lower_clip': 0.5244635552309378, 'upper_clip': 6.394782629775153, 'bid_factor': 0.6949952575690801}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 530.1422753623789, rmse: 1.4405723634818337, SCR: 13040.888386560988

[I 2026-04-28 15:25:20,219] Trial 41 finished with value: 13104.149604650629 and parameters: {'k_p1': 0.0013676239469968406, 'k_p2': 0.6538635968490303, 'k_i1': 0.010322338786676793, 'k_i2': 0.027552862474797435, 'k_d1': 0.0005974164122955152, 'k_d2': 0.2920237141857764, 'alpha': 0.5167498171942114, 'beta': 0.37932212476582916, 'coef': 0.7868327070187832, 'lower_clip': 0.5139537057466387, 'upper_clip': 6.233449490276274, 'bid_factor': 3.471486503066278}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 537.9237415135981, rmse: 1.4288024046690326, SCR: 13104.149604650629

[I 2026-04-28 15:35:55,255] Trial 42 finished with value: 13353.427092994614 and parameters: {'k_p1': 0.0006270915479626169, 'k_p2': 0.05844328522637498, 'k_i1': 0.0131639645970267, 'k_i2': 0.03125280106930145, 'k_d1': 0.0006619691802112161, 'k_d2': 0.0004545515734294739, 'alpha': 0.771972049198434, 'beta': 0.3844258015535147, 'coef': 0.2725078866664692, 'lower_clip': 0.43940897475124757, 'upper_clip': 6.000299755581115, 'bid_factor': 1.5423423887640424}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 1090.8018824257956, rmse: 1.234787772046771, SCR: 13353.427092994614

[I 2026-04-28 15:38:28,366] Trial 43 finished with value: 13192.978309024991 and parameters: {'k_p1': 0.0015807903917094334, 'k_p2': 0.7721235095191864, 'k_i1': 0.4828240190285229, 'k_i2': 0.04788414960424659, 'k_d1': 0.015438629650666632, 'k_d2': 0.010349304414438435, 'alpha': 0.837735206141034, 'beta': 0.3951339630267304, 'coef': 0.7891302335558514, 'lower_clip': 0.4564093674901668, 'upper_clip': 6.252280352572533, 'bid_factor': 1.552322547214676}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 545.6997960242661, rmse: 1.4155397772483762, SCR: 13192.978309024991

[I 2026-04-28 15:39:08,648] Trial 44 finished with value: 13346.476922338006 and parameters: {'k_p1': 0.001912532186340448, 'k_p2': 0.9875860955004435, 'k_i1': 0.015233859281283383, 'k_i2': 0.026191189716334023, 'k_d1': 0.014909654940400884, 'k_d2': 0.0002604684656134672, 'alpha': 0.792512533155259, 'beta': 0.3202402233849522, 'coef': 0.2833489203537102, 'lower_clip': 0.44891465689308624, 'upper_clip': 6.265134720457337, 'bid_factor': 1.532105224237889}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 1090.8024806776145, rmse: 1.2345344143017327, SCR: 13346.476922338006

[I 2026-04-28 15:39:14,985] Trial 45 finished with value: 13346.259308181363 and parameters: {'k_p1': 0.0015449388935060023, 'k_p2': 0.7298923899089504, 'k_i1': 0.007537214053601672, 'k_i2': 0.1002646160683638, 'k_d1': 0.015354387067529595, 'k_d2': 0.04131837678970678, 'alpha': 0.7716107175064774, 'beta': 0.3150218278352833, 'coef': 0.28368835984657353, 'lower_clip': 0.4426747008293601, 'upper_clip': 7.408717992051781, 'bid_factor': 19.633987452630713}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 1090.8025046191485, rmse: 1.2345576097768207, SCR: 13346.259308181363

[I 2026-04-28 15:39:25,885] Trial 46 finished with value: 13641.457979266817 and parameters: {'k_p1': 0.00019978630987911125, 'k_p2': 0.02412482837988412, 'k_i1': 0.1485624154020956, 'k_i2': 0.5578643346455131, 'k_d1': 0.014023890642426548, 'k_d2': 0.04148435388433935, 'alpha': 0.8882536025352742, 'beta': 0.33631005082797893, 'coef': 0.2813908147808696, 'lower_clip': 0.8862057374049166, 'upper_clip': 3.621404489581764, 'bid_factor': 3.309510950176428}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 1012.93799756379, rmse: 1.2270954996791406, SCR: 13641.457979266817

[I 2026-04-28 15:39:33,726] Trial 47 finished with value: 13685.559554542262 and parameters: {'k_p1': 0.00016526936412101262, 'k_p2': 0.052487983909783556, 'k_i1': 0.16415183592518992, 'k_i2': 0.5996031595817298, 'k_d1': 0.011688213547793189, 'k_d2': 0.03905724158740975, 'alpha': 0.7227155235710712, 'beta': 0.32312586106164043, 'coef': 0.3014883793592555, 'lower_clip': 0.8760264464066888, 'upper_clip': 3.718529631203158, 'bid_factor': 1.3322544958600937}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 935.0687376379803, rmse: 1.2359235019791444, SCR: 13685.559554542262

[I 2026-04-28 15:42:25,884] Trial 48 finished with value: 13796.41914376261 and parameters: {'k_p1': 0.00019827006946420342, 'k_p2': 0.01836836448899676, 'k_i1': 0.1441335859527131, 'k_i2': 0.5771186022315865, 'k_d1': 0.010926842367492667, 'k_d2': 0.03762328195162902, 'alpha': 0.6308538068950709, 'beta': 0.31335210683842285, 'coef': 0.30940677219355656, 'lower_clip': 0.8932608115455336, 'upper_clip': 3.727854282632149, 'bid_factor': 2.6129420654893614}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 810.4880316469004, rmse: 1.24134189798066, SCR: 13796.41914376261

[I 2026-04-28 15:42:45,884] Trial 49 finished with value: 13807.732726773706 and parameters: {'k_p1': 0.00017943214358690136, 'k_p2': 0.053441748518279715, 'k_i1': 0.1355077495599355, 'k_i2': 0.6578720347123389, 'k_d1': 0.0002129470475537594, 'k_d2': 0.043225775842125634, 'alpha': 0.6585501876969821, 'beta': 0.45009838312989764, 'coef': 0.31108867780857724, 'lower_clip': 0.899093191716845, 'upper_clip': 7.14849874941675, 'bid_factor': 18.750826775641904}. Best is trial 25 with value: 13987.69098398148.

CPC_REL: 779.3453731121556, rmse: 1.2444433809004858, SCR: 13807.732726773706
Best trial:
  Value: 13987.69098398148
  Params:
    k_p1: 0.001580550809860663
    k_p2: 0.07748261476306627
    k_i1: 0.20648462123991718
    k_i2: 0.015378356463679776
    k_d1: 0.0001244195748456774
    k_d2: 0.01717121082588407
    alpha: 0.34193459326742587
    beta: 0.5093359800237278
    coef: 0.4748021421210206
    lower_clip: 0.8953241481379589
    upper_clip: 4.46793596656986
    bid_factor: 1.161110905612604

[I 2026-04-28 15:44:35,029] A new study created in memory with name: no-name-30ae2879-2097-4fd8-8037-53860584180f

CPC_REL: 468.0890805588127, rmse: 1.4080790131967482, SCR: 14673.570616480516
=== BROI | metric=SCR | auction_mode=FPA ===

[I 2026-04-28 15:45:33,126] Trial 0 finished with value: 5335.313001746926 and parameters: {'ro': 0.4082331665966555, 'v_bar': 122.7582671086234}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:46:31,355] Trial 1 finished with value: 5335.313001746926 and parameters: {'ro': 14.071095169064515, 'v_bar': 3.7570597138026454}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:47:29,404] Trial 2 finished with value: 5335.313001746926 and parameters: {'ro': 0.046885748370639885, 'v_bar': 0.04687454996076498}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:48:27,811] Trial 3 finished with value: 5335.313001746926 and parameters: {'ro': 0.017775399007348217, 'v_bar': 53.14343038625027}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:49:26,243] Trial 4 finished with value: 5335.313001746926 and parameters: {'ro': 3.8495830758681158, 'v_bar': 11.1030270073596}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:50:24,723] Trial 5 finished with value: 5335.313001746926 and parameters: {'ro': 0.012261243785158804, 'v_bar': 148.46065326863524}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:57:22,138] Trial 6 finished with value: 5335.313001746926 and parameters: {'ro': 38.05053502753182, 'v_bar': 0.08189867664214782}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:58:21,863] Trial 7 finished with value: 5335.313001746926 and parameters: {'ro': 0.060538915670281045, 'v_bar': 0.06149337057087107}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 15:59:21,764] Trial 8 finished with value: 5335.313001746926 and parameters: {'ro': 0.20349559513080262, 'v_bar': 1.8071456341395589}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:00:22,300] Trial 9 finished with value: 5335.313001746926 and parameters: {'ro': 0.7207895500630219, 'v_bar': 0.1788896719299994}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:01:22,812] Trial 10 finished with value: 5335.313001746926 and parameters: {'ro': 116.1610761307477, 'v_bar': 20.78552340655771}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:02:22,295] Trial 11 finished with value: 5335.313001746926 and parameters: {'ro': 6.086485094805085, 'v_bar': 2.3601205157871528}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:03:21,808] Trial 12 finished with value: 5335.313001746926 and parameters: {'ro': 11.911486258112047, 'v_bar': 0.4720011100824056}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:04:22,058] Trial 13 finished with value: 5335.313001746926 and parameters: {'ro': 1.0825739219632204, 'v_bar': 5.545435464905506}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:05:21,441] Trial 14 finished with value: 5335.313001746926 and parameters: {'ro': 0.2754001010925982, 'v_bar': 0.011393929333145734}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:06:25,863] Trial 15 finished with value: 5335.313001746926 and parameters: {'ro': 24.425666341307682, 'v_bar': 116.93808454921493}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:07:26,707] Trial 16 finished with value: 5335.313001746926 and parameters: {'ro': 2.425690363619252, 'v_bar': 28.583616418822984}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:08:26,575] Trial 17 finished with value: 5335.313001746926 and parameters: {'ro': 110.87477599329394, 'v_bar': 0.6788231377889405}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:09:27,311] Trial 18 finished with value: 5335.313001746926 and parameters: {'ro': 0.37164451913037, 'v_bar': 4.187123963897827}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:10:28,559] Trial 19 finished with value: 5335.313001746926 and parameters: {'ro': 14.719421905916677, 'v_bar': 56.03095116474411}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:11:28,354] Trial 20 finished with value: 5335.313001746926 and parameters: {'ro': 0.10784100797322489, 'v_bar': 9.240970940079578}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:12:28,534] Trial 21 finished with value: 5335.313001746926 and parameters: {'ro': 0.029335493901414197, 'v_bar': 0.016442414696012368}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:13:28,571] Trial 22 finished with value: 5335.313001746926 and parameters: {'ro': 0.1301245929217316, 'v_bar': 0.5966789707393977}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:14:29,214] Trial 23 finished with value: 5335.313001746926 and parameters: {'ro': 0.6233215928124688, 'v_bar': 0.03282782834712523}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:15:29,787] Trial 24 finished with value: 5335.313001746926 and parameters: {'ro': 0.05449455402408676, 'v_bar': 0.17673255291332213}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:16:29,811] Trial 25 finished with value: 5335.313001746926 and parameters: {'ro': 2.340690973683643, 'v_bar': 0.1735305897280088}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:17:29,817] Trial 26 finished with value: 5335.313001746926 and parameters: {'ro': 0.03516217906861751, 'v_bar': 0.9695275473410863}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:18:29,026] Trial 27 finished with value: 5335.313001746926 and parameters: {'ro': 50.47153084964992, 'v_bar': 2.802349428238236}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:19:29,530] Trial 28 finished with value: 5335.313001746926 and parameters: {'ro': 7.790916559750352, 'v_bar': 0.3812283746407413}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:20:29,352] Trial 29 finished with value: 5335.313001746926 and parameters: {'ro': 0.02199497149283835, 'v_bar': 60.70799412878103}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:21:30,353] Trial 30 finished with value: 5335.313001746926 and parameters: {'ro': 1.6126392673443735, 'v_bar': 20.732650129649834}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:22:31,112] Trial 31 finished with value: 5335.313001746926 and parameters: {'ro': 0.013667794952683594, 'v_bar': 62.03040505297169}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:23:31,254] Trial 32 finished with value: 5335.313001746926 and parameters: {'ro': 0.07082504284232874, 'v_bar': 156.8930807030239}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:24:31,336] Trial 33 finished with value: 5335.313001746926 and parameters: {'ro': 0.01241743888102595, 'v_bar': 7.819472324445791}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:25:31,266] Trial 34 finished with value: 5335.313001746926 and parameters: {'ro': 0.12262087166551307, 'v_bar': 36.422477201032905}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:26:29,718] Trial 35 finished with value: 5335.313001746926 and parameters: {'ro': 0.020021767923928353, 'v_bar': 15.421651840919395}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:27:27,970] Trial 36 finished with value: 5335.313001746926 and parameters: {'ro': 0.04064040902590461, 'v_bar': 88.22129810597852}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:28:26,456] Trial 37 finished with value: 5335.313001746926 and parameters: {'ro': 0.44207120644982556, 'v_bar': 0.07216563629165516}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:29:25,116] Trial 38 finished with value: 5335.313001746926 and parameters: {'ro': 0.01007240248056429, 'v_bar': 181.5237724275209}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:30:23,338] Trial 39 finished with value: 5335.313001746926 and parameters: {'ro': 5.090512048857371, 'v_bar': 1.2383340532656288}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:31:21,992] Trial 40 finished with value: 5335.313001746926 and parameters: {'ro': 0.21479904356100263, 'v_bar': 0.29445382709889173}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:32:20,212] Trial 41 finished with value: 5335.313001746926 and parameters: {'ro': 4.648138435423441, 'v_bar': 11.793850123608467}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:33:18,787] Trial 42 finished with value: 5335.313001746926 and parameters: {'ro': 29.730855284771263, 'v_bar': 4.124413529126686}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:34:17,346] Trial 43 finished with value: 5335.313001746926 and parameters: {'ro': 1.0475019988158512, 'v_bar': 27.383892444911996}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:35:16,248] Trial 44 finished with value: 5335.313001746926 and parameters: {'ro': 12.773288874994194, 'v_bar': 2.2118266018163375}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:36:14,710] Trial 45 finished with value: 5335.313001746926 and parameters: {'ro': 61.920957121709506, 'v_bar': 104.26316522199272}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:37:13,311] Trial 46 finished with value: 5335.313001746926 and parameters: {'ro': 2.916580558360132, 'v_bar': 5.915737416010401}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:38:12,197] Trial 47 finished with value: 5335.313001746926 and parameters: {'ro': 9.634958385716354, 'v_bar': 15.11189985422204}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:39:11,272] Trial 48 finished with value: 5335.313001746926 and parameters: {'ro': 0.07726942088288406, 'v_bar': 43.27410301233733}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926

[I 2026-04-28 16:40:10,952] Trial 49 finished with value: 5335.313001746926 and parameters: {'ro': 23.111640859271496, 'v_bar': 22.124040091582167}. Best is trial 0 with value: 5335.313001746926.

CPC_REL: 5366.064976843506, rmse: 1.2283139294795586, SCR: 5335.313001746926
Best trial:
  Value: 5335.313001746926
  Params:
    ro: 0.4082331665966555
    v_bar: 122.7582671086234
CPC_REL: 5906.638103233931, rmse: 1.2297089006198547, SCR: 4599.856980283712

   model      CPC_REL      RMSE           SCR
0   mpid   468.089081  1.408079  14673.570616
1  tapid    10.940620  7.722339   8623.413930
2   broi  5906.638103  1.229709   4599.856980

### Notes

- `objective_*(eval=True)` loads params from:
  `best_params/{best_params_subfolder}/{model}_{metric}_{auction_mode}.pkl`
- This notebook currently runs: `linear`, `tapid`, `mpid`, `mystique`.
- `broi` is not included in this run block.

### Скоры val / test по сохранённым `.pkl`

Ниже: все `*{metric}_{auction}.pkl` из папки `trainer` + `autobidder_check` на каждом из `val`, `test`, если ключ есть в `data_config`.

In [6]:
from pathlib import Path
import pickle

from example_notebooks.experiments.adapters.baseline_adapter import (
    _MODEL_TO_BIDDER,
    _build_bidder_eval_params,
)
from simulator.validation.check_results import autobidder_check

params_dir = Path(trainer.get_params_path("linear")).parent
suffix = f"_{trainer.metric.lower()}_{trainer.auction_mode}.pkl"

rows = []
for split in ("val", "test"):
    if split not in data_config:
        continue
    sp = data_config[split]
    for path in sorted(params_dir.glob(f"*{suffix}")):
        stem = path.name[: -len(suffix)]
        d = pickle.loads(path.read_bytes())
        bidder = _MODEL_TO_BIDDER[stem]
        p = _build_bidder_eval_params(stem, d)
        sc = autobidder_check(
            bidder=bidder,
            params={"input_campaigns": sp["campaigns_path"], "input_stats": sp["stats_path"], **p},
            auction_mode=trainer.auction_mode,
        )["score"]
        rows.append({"split": split, "model": stem, "CPC_REL": sc[0], "RMSE": sc[1], "SCR": sc[2]})

baseline_scores_df = pd.DataFrame(rows).sort_values(["split", "model"]).reset_index(drop=True)
baseline_scores_df

  split   model      CPC_REL      RMSE           SCR
0  test    broi  5906.638103  1.229709   4599.856980
1  test  linear   421.338042  1.503115  17792.733546
2  test   m_pid   468.089081  1.408079  14673.570616
3  test  ta_pid    10.940620  7.722339   8623.413930